homepage: https://github.com/cbmarcum/skeletal
license: Apache License
rely: []
_os: "%{os}"
_arch: "%{arch}"
file_suffix: zip
url:
  internet: "https://dlcdn.apache.org/spark/spark-%{version}/spark-%{version}-bin-hadoop3.tgz"
  cn: "https://dlcdn.apache.org/spark/spark-%{version}/spark-%{version}-bin-hadoop3.tgz"
unpack_way: unpack_copy_to_target_dir

xbin:
  spark: bin/spark

rule:
  /*:
    version: stable

  stable/*:
    version: "3.4.0"

  latest/*:
    version: "3.4.0"

  "*/linux/arm64":


  "*/darwin/arm64":


  "*/linux/x64":


  "*/darwin/x64":


  "*/win/x64":


