homepage: https://github.com/jbake-org/jbake
license: Apache License
rely: []
_os: "%{os}"
_arch: "%{arch}"
file_suffix: zip
url:
  internet: "https://github.com/jbake-org/jbake/releases/download/v2.6.6/jbake-2.6.6-bin.zip"
  cn: "https://github.com/jbake-org/jbake/releases/download/v2.6.6/jbake-2.6.6-bin.zip"
unpack_way: unpack_copy_to_target_dir
xbin:
  jbake: bin/jbake
rule:
  /*:
    version: stable

  stable/*:
    version: v2.6.7

  latest/*:
    version: v2.6.7

  "*/linux/arm64":


  "*/darwin/arm64":


  "*/linux/x64":

  "*/darwin/x64":


  "*/win/x64":





