homepage: https://gitee.com/organizations/static-build/projects
license: MIT
rely: []

gh_url: https://github.com/x-cmd-build/termsvg/releases/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/termsvg/-/releases/%{version}/downloads
file_suffix: tar.gz
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin:
  termsvg: termsvg.%{os}.%{arch}%{bin_suffix}


rule:
  /*:
    version: stable

  stable/*:
    version: v0.0.0

  latest/*:
    version: v0.0.0

    
  "*/darwin/x64":
    zipname:    termsvg-0.6.1-darwin-amd64.zip
    file_suffix: zip
  "*/darwin/arm64":
    zipname:    termsvg-0.6.1-darwin-arm64.zip
    file_suffix: zip
  "*/linux/arm64":
    zipname:    termsvg-0.6.1-linux-arm64.tar.gz
  "*/linux/x64":
    zipname:    termsvg-0.6.1-linux-amd64.tar.gz
