homepage: https://www.oracle.com/java/technologies/javase/products-jmc8-downloads.html
license: Apache License
rely: []
_os: "%{os}"
_arch: "%{arch}"
file_suffix: tar.gz
url:
  internet: "https://download.oracle.com/otn-pub/java/jmc/%{version}+05/10e8cce67c7843478f41411b7003171c/jmc-%{version}_linux-x64.tar.gz"
  cn: "https://download.oracle.com/otn-pub/java/jmc/%{version}+05/10e8cce67c7843478f41411b7003171c/jmc-%{version}_linux-x64.tar.gz"
unpack_way: unpack_copy_to_target_dir
xbin:
  jarviz: JDK Mission Control/jmc
rule:
  /*:
    version: stable

  stable/*:
    version: 8.3.0

  latest/*:
    version: 8.3.0

  "*/linux/arm64":

  "*/darwin/arm64":
    url:
      internet: "https://download.oracle.com/otn-pub/java/jmc/%{version}+05/10e8cce67c7843478f41411b7003171c/jmc-%{version}_osx-aarch64.tar.gz"
      cn: "https://download.oracle.com/otn-pub/java/jmc/%{version}+05/10e8cce67c7843478f41411b7003171c/jmc-%{version}_osx-aarch64.tar.gz"

  "*/linux/x64":

  "*/darwin/x64":
    url:
      internet: "https://download.oracle.com/otn-pub/java/jmc/%{version}+05/10e8cce67c7843478f41411b7003171c/jmc-%{version}_osx-x64.tar.gz"
      cn: "https://download.oracle.com/otn-pub/java/jmc/%{version}+05/10e8cce67c7843478f41411b7003171c/jmc-%{version}_osx-x64.tar.gz"

  "*/win/x64":
    url:
      internet: "https://download.oracle.com/otn-pub/java/jmc/%{version}+05/10e8cce67c7843478f41411b7003171c/jmc-%{version}_windows-x64.zip"
      cn: "https://download.oracle.com/otn-pub/java/jmc/%{version}+05/10e8cce67c7843478f41411b7003171c/jmc-%{version}_windows-x64.zip"




