homepage: https://github.com/Concurnas/Concurnas/releases
license: Apache License
rely: []

file_suffix: zip
url:
  internet: "https://github.com/Concurnas/Concurnas/releases/download/%{version}/Concurnas-%{version}.zip"
  cn: "https://github.com/Concurnas/Concurnas/releases/download/%{version}/Concurnas-%{version}.zip"
unpack_way: unpack_copy_to_target_dir
xbin:
  conc: bin/conc
rule:
  /*:
    version: stable

  stable/*:
    version: 1.14.020

  latest/*:
    version: 1.14.020

  "*/linux/arm64":

  "*/darwin/arm64":
    _arch: amd64

  "*/linux/x64":

  "*/darwin/x64":

  "*/win/x64":


