homepage: https://jmeter.apache.org/download_jmeter.cgi
license: Apache License
rely: []
_os: "%{os}"
_arch: "%{arch}"
file_suffix: zip
url:
  internet: "https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-%{version}.zip"
  cn: "https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-%{version}.zip"
unpack_way: unpack_copy_to_target_dir
xbin:
  jmeter: bin/jmeter
rule:
  /*:
    version: stable

  stable/*:
    version: 5.5

  latest/*:
    version: 5.5
  "*/linux/arm64":

  "*/darwin/arm64":

  "*/linux/x64":

  "*/darwin/x64":

  "*/win/x64":




