homepage: https://github.com/oven-sh/bun/releases
license: MIT
rely: []

file_suffix: 7z
url:
  internet: "https://github.com/oven-sh/bun/releases/download/bun-%{version}/bun-%{_os}-%{_arch}-baseline.zip"
  cn: "https://github.com/oven-sh/bun/releases/download/bun-%{version}/bun-%{_os}-%{_arch}-baseline.zip"

_os: "%{os}"
_arch: "%{arch}"
unpack_way: unpack_copy_to_target_dir
xbin: bun-profile
hook:
  activate: activate.sh
rule:
  /*:
    version: latest

  stable/*:
    version: v0.5.8

  latest/*:
    version: v0.5.8

  "*/*/arm64":
    _arch: aarch64
    url:
      cn: https://github.com/oven-sh/bun/releases/download/bun-%{version}/bun-%{_os}-%{_arch}-.zip
      internet: https://github.com/oven-sh/bun/releases/download/bun-%{version}/bun-%{_os}-%{_arch}-.zip

