homepage: https://golang.google.cn
license: MIT
rely: []

gh_url: https://raw.githubusercontent.com/static-build/magick/main/magick/%{version}
gc_url: https://gitee.com/static-build/magick/raw/main/magick/%{version}
static-build: magick/magick
file_suffix: 7z
url:
  _: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin: magick.%{os}.%{arch}%{bin_suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: 7.1.0

  latest/*:
    version: 7.1.0

  "*/linux/arm64":
    zipname:    magick.linux.arm64.7z
  "*/darwin/arm64":
    zipname:    magick.darwin.arm64.7z
  "*/linux/x64":
    zipname:    magick.linux.x64.7z
  "*/darwin/x64":
    zipname:    magick.darwin.x64.7z
  "*/win/x64":
    zipname:    magick.win.x64.exe.7z
    bin_suffix: .exe
