homepage: https://ballerina.io/learn/install-ballerina/installation-options/#install-via-the-ballerina-language-zip-file
license: Apache License
rely: []

file_suffix: zip
url:
  internet: "https://dist.ballerina.io/downloads/%{version}/ballerina-%{version}-swan-lake.zip"
  cn: "https://dist.ballerina.io/downloads/%{version}/ballerina-%{version}-swan-lake.zip"

xbin:
  ballerina: bin/ballerina
  bal: bin/ballerina
unpack_way: unpack_copy_to_target_dir
rule:
  /*:
    version: stable

  stable/*:
    version: 2201.5.0

  latest/*:
    version: 2201.5.0

  "*/linux/arm64":

  "*/darwin/arm64":

  "*/linux/x64":

  "*/darwin/x64":

  "*/win/x64":


