homepage: https://golang.google.cn
license: MIT
rely: []

gh_url: https://github.com/x-cmd-build/tmux/releases/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/tmux/-/releases/%{version}/downloads
file_suffix: 7z
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin:
  tmux: tmux.%{os}.%{arch}%{bin_suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: v0.0.0

  latest/*:
    version: v0.0.0

  "*/linux/arm64":
    zipname:    tmux.linux.arm64.7z
  "*/darwin/arm64":
    zipname:    tmux.darwin.arm64.7z
  "*/linux/x64":
    zipname:    tmux.linux.x64.7z
  "*/darwin/x64":
    zipname:    tmux.darwin.x64.7z
  "*/win/x64":
    zipname:    tmux.win.x64.exe.7z
    xbin: tmux.win.x64.exe