homepage: https://golang.google.cn
license: MIT
rely: []

gh_url: https://raw.githubusercontent.com/static-build/tmux/main/tmux/%{version}
gc_url: https://gitee.com/static-build/tmux/raw/main/tmux/%{version}
file_suffix: 7z
static-build: tmux/tmux
url:
  _: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin:
  tmux: tmux.%{os}.%{arch}%{bin_suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: 3.2a

  latest/*:
    version: 3.2a

  "*/linux/arm64":
    zipname:    tmux.linux.arm64.7z
  "*/darwin/arm64":
    zipname:    tmux.darwin.arm64.7z
  "*/linux/x64":
    zipname:    tmux.linux.x64.7z
  "*/darwin/x64":
    zipname:    tmux.darwin.x64.7z
  "*/win/x64":
    zipname:    tmux.win.x64.exe.7z
    bin_suffix: .exe