homepage: https://testingisdocumenting.org/znai/introduction/getting-started/
license: Apache License
rely: []
_os: "%{os}"
_arch: "%{arch}"
file_suffix: zip
url:
  internet: "https://repo.maven.apache.org/maven2/org/testingisdocumenting/znai/znai-dist/%{version}/znai-dist-%{version}-znai.zip"
  cn: "https://repo.maven.apache.org/maven2/org/testingisdocumenting/znai/znai-dist/%{version}/znai-dist-%{version}-znai.zip"
unpack_way: unpack_copy_to_target_dir

xbin:
  znai: dist/znai

rule:
  /*:
    version: stable

  stable/*:
    version: "1.63"

  latest/*:
    version: "1.63"

  "*/linux/arm64":


  "*/darwin/arm64":


  "*/linux/x64":


  "*/darwin/x64":


  "*/win/x64":


