homepage: https://github.com/infrastructor/infrastructor
license: Apache License
rely: []
_os: "%{os}"
_arch: "%{arch}"
file_suffix: zip
url:
  internet: "https://github.com/infrastructor/infrastructor/releases/download/%{version}/infrastructor-%{version}.zip"
  cn: "https://github.com/infrastructor/infrastructor/releases/download/%{version}/infrastructor-%{version}.zip"
unpack_way: unpack_copy_to_target_dir
xbin:
  infrastructor: bin/infrastructor
rule:
  /*:
    version: stable

  stable/*:
    version: v1.3

  latest/*:
    version: v1.3

  "*/linux/arm64":

  "*/darwin/arm64":

  "*/linux/x64":

  "*/darwin/x64":

  "*/win/x64":




