homepage: https://github.com/micronaut-projects/micronaut-starter
license: Apache License
rely: []
_os: "%{os}"
_arch: "%{arch}"
file_suffix: zip
url:
  internet: "https://github.com/micronaut-projects/micronaut-starter/releases/download/%{version}/mn-%{_os}-%{_arch}-%{version}.zip"
  cn: "https://github.com/micronaut-projects/micronaut-starter/releases/download/%{version}/mn-%{_os}-%{_arch}-%{version}.zip"
unpack_way: unpack_copy_to_target_dir

xbin:
  mn: bin/mn
  micronaut: bin/mn

rule:
  /*:
    version: stable

  stable/*:
    version: v3.8.8
  latest/*:
    version: v3.8.8

  "*/linux/arm64":
    _arch: amd64

  "*/darwin/arm64":
    _arch: amd64

  "*/linux/x64":
    _arch: amd64

  "*/darwin/x64":
    _arch: amd64

  "*/win/x64":
    _arch: amd64

