homepage: https://gitee.com/organizations/static-build/projects
license: MIT
rely: []

gh_url: https://github.com/x-cmd-build/gitui/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/gitui/-/releases/%{version}/downloads
file_suffix: tar.xz
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin:
  gitui: gitui%{bin_suffix}


rule:
  /*:
    version: stable

  stable/*:
    version: v0.0.0

  latest/*:
    version: v0.0.0

  "*/darwin/arm64":
    zipname:    gitui-mac.tar.xz
  "*/darwin/x64":
    zipname:    gitui-mac.tar.xz
  "*/linux/x64":
    zipname:    gitui-linux-musl.tar.xz
  "*/linux/arm64":
    zipname:    gitui-linux-aarch64.tar.xz
  "*/win/x64":
    zipname:    gitui-win.tar.xz
    bin_suffix: .exe