homepage: https://gitee.com/organizations/static-build/projects
license: MIT
rely: []

gh_url: https://github.com/x-cmd-build/curl/releases/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/curl/-/releases/%{version}/downloads
file_suffix: 7z
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin:
  du: curl.%{os}.%{arch}%{bin_suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: 7.83.1-DEV

  latest/*:
    version: 7.83.1-DEV

  "*/linux/arm64":
    zipname:    curl.linux.arm64.7z
  "*/darwin/arm64":
    zipname:    curl.darwin.arm64.7z
  "*/linux/x64":
    zipname:    curl.linux.x64.7z
  "*/darwin/x64":
    zipname:    curl.darwin.x64.7z
  "*/win/x64":
    zipname:    curl.win.x64.exe.7z
    bin_suffix: .exe
