homepage: https://repo.anaconda.com/miniconda
license: MIT
rely: []
bin: {}

minoconda_sh_file: Miniconda3-%{version}-%{os_name}-%{arch_name}.sh
anaconda_source: https://repo.anaconda.com/miniconda/%{version}
tuna_source: https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/%{version}
url:
  _: "%{anaconda_source}/%{minoconda_sh_file}"
  cn: "%{tuna_source}/%{minoconda_sh_file}"

rule:
  v*/linux-*:
    os_name: Linux
  v*/darwin-*:
    os_name: MacOSX
  v*/win-*:
    os_name: Windows

  v*/*-arm64:
    arch_name: arm64
  v*/*-x64:
    arch_name: x86_64
