homepage: https://repo.anaconda.com/miniconda
license: MIT
rely: []
bin: {}
_os: "%{os}"
_arch: "%{arch}"

file_suffix: sh
minoconda_sh_file: Miniconda3-%{version}-%{_os}-%{_arch}.%{file_suffix}

anaconda_source: https://repo.anaconda.com/miniconda
tuna_source: https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda
url:
  _: "%{anaconda_source}/%{minoconda_sh_file}"
  cn: "%{tuna_source}/%{minoconda_sh_file}"
xbin:
  python: bin/pip
hook:
  install: install.sh
  activate: activate.sh
  deactivate: deactivate.sh

rule:

  /*:
    version: latest
  latest/*:
    version: py39_4.12.0

  "v*-pypy*/darwin/*":
    _os: osx64
    url: https://downloads.python.org/pypy/%{version}-%{_os}.tar.bz2

  "v*-pypy*/linux/x64":
    _os: linux64
    url: https://downloads.python.org/pypy/%{version}-%{_os}.tar.bz2

  "v*-pypy*/linux/x32":
    _os: linux32
    url: https://downloads.python.org/pypy/%{version}-%{_os}.tar.bz2


  py*/linux/x*:
    _os: Linux
    _arch: x86_64

  py*/darwin/*:
    _os: MacOSX

  py*/win/*:
    _os: Windows
    _arch: x86_64
    file_suffix: exe

  py*/darwin/x64:
    _os: MacOSX
    _arch: x86_64

