homepage: https://repo.anaconda.com/miniconda
license: MIT
rely: []
bin: {}
_os: "%{os}"
_arch: "%{arch}"

file_suffix: sh
minoconda_sh_file: Miniconda3-%{version}-%{_os}-%{_arch}.%{file_suffix}

anaconda_source: https://repo.anaconda.com/miniconda
tuna_source: https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda
url:
  internet: "%{anaconda_source}/%{minoconda_sh_file}"
  cn: "%{tuna_source}/%{minoconda_sh_file}"
xbin:
  python: bin/python
hook:
  install: install.sh
  activate: activate.sh
  deactivate: deactivate.sh

rule:

  /*:
    version: latest
  latest/*:
    version: py310_23.1.0

  "*/*/x64":
    _arch: x86_64

  "*/darwn/*":
    _os: MacOSX

  "*/linux/*":
    _os: Linux

  "*/win/*":
    _os: Windows

  py*/linux/x64:
    _os: Linux
    _arch: x86_64

  py*/darwin/*:
    _os: MacOSX

  py*/win/x64:
    _os: Windows
    _arch: x86_64
    file_suffix: exe

  py*/darwin/x64:
    _os: MacOSX
    _arch: x86_64

  py*/darwin/arm64:
    _os: MacOSX


  py*/linux/arm64:
    url:
      internet: "%{anaconda_source}/Miniconda3-%{version}-%{_os}-aarch64.%{file_suffix}"
    _os: Linux


  "pypy*/*/*":
    file_suffix: tar.bz2

  "pypy*/darwin/*":
    _os: osx64
    url:
      _: https://downloads.python.org/pypy/%{version}-%{_os}.tar.bz2
      cn: https://downloads.python.org/pypy/%{version}-%{_os}.tar.bz2

  "pypy*/linux/x64":
    _os: linux64
    url:
      _ : https://downloads.python.org/pypy/%{version}-%{_os}.tar.bz2
      cn: https://downloads.python.org/pypy/%{version}-%{_os}.tar.bz2

  "pypy*/linux/x32":
    _os: linux32
    url:
      _: https://downloads.python.org/pypy/%{version}-%{_os}.tar.bz2
      cn: https://downloads.python.org/pypy/%{version}-%{_os}.tar.bz2

  "pypy*/win/x64":
    _arch: 64
    url:
      _: https://downloads.python.org/pypy/%{version}-%{_os}.zip
      cn: https://downloads.python.org/pypy/%{version}-%{_os}.zip

  "pypy*/win/x32":
    _arch: 32
    url:
      _: https://downloads.python.org/pypy/%{version}-%{_os}.zip
      cn: https://downloads.python.org/pypy/%{version}-%{_os}.zip

