homepage: https://repo.anaconda.com/miniconda
license: MIT
rely: []
bin: {}

minoconda_sh_file: Miniconda3-%{version}-%{os}-%{arch}.sh
anaconda_source: https://repo.anaconda.com/miniconda/%{version}
tuna_source: https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/%{version}
url:
  _: "%{anaconda_source}/%{minoconda_sh_file}"
  cn: "%{tuna_source}/%{minoconda_sh_file}"

os-arch:
  v*/linux-*:
    os: Linux
  v*/darwin-*:
    os: MacOSX
  v*/win-*:
    os: Windows

  v*/*-arm64:
    arch: arm64
  v*/*-x64:
    arch: x86_64
