homepage: https://www.scala-lang.org/download/all.html
license: MIT
rely: []
file_suffix: zip
scala_source: "https://downloads.lightbend.com/scala/"
cn_source: "https://downloads.lightbend.com/scala/"
_os: "%{os}"
_arch: "%{arch}"
url:
  _: '%{scala_source}/%{version}/scala-%{version}.%{file_suffix}'
  cn: '%{cn_source}/%{version}/scala-%{version}.%{file_suffix}'

xbin: bin/scala

hook:
  activate: activate.sh
  deactivate: deactivate.sh
unpack_way: unpack_copy_to_target_dir

rule:

  /*:
    version: latest

  latest:
    version: 3.1.2

  "2.10*/*":
    url:
      cn: "https://downloads.lightbend.com/scala/%{version}/scala-%{version}.%{file_suffix}"

  "2.13*/*":
    url:
      cn: "https://downloads.lightbend.com/scala/%{version}/scala-%{version}.%{file_suffix}"

  "2.12*/*":
    url:
      cn: "https://downloads.lightbend.com/scala/%{version}/scala-%{version}.%{file_suffix}"

  "2.11.11/*":
    url:
      cn: "https://downloads.lightbend.com/scala/%{version}/scala-%{version}.%{file_suffix}"

  "2.11*/*":
    url:
      cn: "http://downloads.typesafe.com/scala/%{version}/scala-%{version}.%{file_suffix}"

  "2.11.12/*":
    url:
      cn: "https://downloads.lightbend.com/scala/%{version}/scala-%{version}.%{file_suffix}"

  "3.*/*":
    url:
      cn: "https://github.com/lampepfl/dotty/releases/download/%{version}/scala3-%{version}.%{file_suffix}"


