homepage: https://www.scala-lang.org/download/all.html
license: MIT
rely: []
file_suffix: zip
scala_source: "https://downloads.lightbend.com/scala/"
cn_source: "https://downloads.lightbend.com/scala/"
_os: "%{os}"
_arch: "%{arch}"
url:
  internet: '%{scala_source}/%{version}/scala-%{version}.%{file_suffix}'
  cn: '%{cn_source}/%{version}/scala-%{version}.%{file_suffix}'

xbin:
  scala: bin/scala
  scaladoc: bin/scaladoc

hook:
  activate: activate.sh
  deactivate: deactivate.sh
unpack_way: unpack_copy_to_target_dir

rule:

  /*:
    version: latest

  latest:
    version: 3.1.2

  "*/linux/x64":

  "*/linux/arm64":

  "*/darwin/x64":

  "*/darwin/arm64":

  "*/win/x64":

  "2.10*/*":
    url:
      internet: "https://downloads.lightbend.com/scala/%{version}/scala-%{version}.%{file_suffix}"
      cn: "https://downloads.lightbend.com/scala/%{version}/scala-%{version}.%{file_suffix}"

  "2.13*/*":
    url:
      internet: "https://downloads.lightbend.com/scala/%{version}/scala-%{version}.%{file_suffix}"
      cn: "https://downloads.lightbend.com/scala/%{version}/scala-%{version}.%{file_suffix}"

  "2.12*/*":
    url:
      internet: "https://downloads.lightbend.com/scala/%{version}/scala-%{version}.%{file_suffix}"
      cn: "https://downloads.lightbend.com/scala/%{version}/scala-%{version}.%{file_suffix}"

  "2.11.11/*":
    url:
      internet: "https://downloads.lightbend.com/scala/%{version}/scala-%{version}.%{file_suffix}"
      cn: "https://downloads.lightbend.com/scala/%{version}/scala-%{version}.%{file_suffix}"

  "2.11*/*":
    url:
      internet: "http://downloads.typesafe.com/scala/%{version}/scala-%{version}.%{file_suffix}"
      cn: "http://downloads.typesafe.com/scala/%{version}/scala-%{version}.%{file_suffix}"

  "2.11.12/*":
    url:
      internet: "https://downloads.lightbend.com/scala/%{version}/scala-%{version}.%{file_suffix}"
      cn: "https://downloads.lightbend.com/scala/%{version}/scala-%{version}.%{file_suffix}"

  "3.*/*":
    url:
      internet: "https://github.com/lampepfl/dotty/releases/download/%{version}/scala3-%{version}.%{file_suffix}"
      cn: "https://github.com/lampepfl/dotty/releases/download/%{version}/scala3-%{version}.%{file_suffix}"


