homepage: https://golang.google.cn
license: MIT
rely: []

gh_url: https://raw.githubusercontent.com/static-build/procs/main/procs/%{version}
gc_url: https://gitee.com/static-build/procs/raw/main/procs/%{version}
file_suffix: 7z
static-build: procs/procs
url:
  _: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin: procs.%{os}.%{arch}%{bin_suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: 0.11.9

  latest/*:
    version: 0.11.9

  "*/linux/arm64":
    zipname:    procs.linux.arm64.7z
  "*/darwin/arm64":
    zipname:    procs.darwin.arm64.7z
  "*/linux/x64":
    zipname:    procs.linux.x64.7z
  "*/darwin/x64":
    zipname:    procs.darwin.x64.7z
  "*/win/x64":
    zipname:    procs.win.x64.exe.7z
    bin_suffix: .exe