homepage: https://gitee.com/organizations/static-build/projects
license: MIT
rely: []

gh_url: https://github.com/x-cmd-build/termshark/releases/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/termshark/-/releases/%{version}/downloads
file_suffix: tar.xz
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

unpack_way: unpack_copy_to_target_dir

xbin:
  termshark: termshark%{bin_suffix}


rule:
  /*:
    version: stable

  stable/*:
    version: v0.0.0

  latest/*:
    version: v0.0.0

  "*/darwin/arm64":
    zipname:    termshark_2.4.0_macOs_arm64.tar.xz
  "*/darwin/x64":
    zipname:    termshark_2.4.0_macOs_x64.tar.xz
  "*/linux/arm64":
    zipname:    termshark_2.4.0_linux_arm64.tar.xz
  "*/linux/x64":
    zipname:    termshark_2.4.0_linux_x64.tar.xz
  "*/win/x64":
    zipname:    termshark_2.4.0_windows_x64.tar.xz
    xbin:
      termshark: termshark
    bin_suffix: .exe