homepage: https://e.gitee.com/lteam18/repos/static-build/smartmontools/tree/main/smartmontools/7.2
license: MIT
rely: []

gh_url: https://gitee.com/static-build/smartmontools/raw/main/smartmontools%2F%{version}%2Fsmartctl.%{_os}.%{_arch}.%{file_suffix}
gt_url: https://gitee.com/static-build/smartmontools/raw/main/smartmontools%2F%{version}%2Fsmartctl.%{_os}.%{_arch}.%{file_suffix}
file_suffix: 7z

url:
  en: "%{gt_url}"
  cn: "%{gt_url}"

xbin:
  smartctl: smartctl.%{_os}.%{_arch}

rule:
  /*:
    version: stable

  stable/*:
    version: 7.2

  latest/*:
    version: 7.2

  "*/darwin/arm64":
    _os: darwin
    _arch: arm64
    zipname:    smart.darwin.arm64.7z
  "*/linux/arm64":
    _os: linux
    _arch: arm64
    zipname: smart.linux.arm64.7z
    "*/linux/x64":
    _os: linux
    _arch: x64
    zipname:    smart.linux.x64.7z
  "*/win/x64":
    _os: win
    _arch: x64
    zipname:    win.x64.7z

