homepage: https://ant.apache.org/bindownload.cgi
license: Apache License
rely: []

file_suffix: tar.gz
url:
  internet: "https://dlcdn.apache.org//ant/binaries/apache-ant-%{version}-bin.tar.gz"
  cn: "https://dlcdn.apache.org//ant/binaries/apache-ant-%{version}-bin.tar.gz"

xbin:
  ant: bin/ant
unpack_way: unpack_copy_to_target_dir
rule:
  /*:
    version: stable

  stable/*:
    version: 1.10.13

  latest/*:
    version: 1.10.13

  "*/linux/arm64":

  "*/darwin/arm64":

  "*/linux/x64":

  "*/darwin/x64":

  "*/win/x64":


