homepage: https://gitee.com/organizations/static-build/projects
license: MIT

gh_url: https://github.com/x-cmd-build/zellij/releases/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/zellij/-/releases/%{version}/downloads
file_suffix: tar.gz
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin: zellij%{bin_suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: v0.0.0

  latest/*:
    version: v0.0.0

  "*/linux/arm64":
    zipname:    zellij-aarch64-unknown-linux-musl.tar.gz
  "*/darwin/arm64":
    zipname:    zellij-aarch64-apple-darwin.tar.gz
  "*/linux/x64":
    zipname:    zellij-x86_64-unknown-linux-musl.tar.gz
  "*/darwin/x64":
    zipname:    zellij-x86_64-apple-darwin.tar.gz