homepage: https://golang.google.cn
license: MIT
rely: []

gh_url: https://raw.githubusercontent.com/static-build/p7zip/main/bin
gc_url: https://gitee.com/static-build/p7zip/raw/main/bin
file_suffix: 7z
static-build: p7zip/p7zip
url:
  _: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin:
  pzip: 7za.%{osname}.%{osarch}%{bin_suffix}
  7z: 7za.%{osname}.%{osarch}%{bin_suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: 1.6-dirty

  latest/*:
    version: 1.6-dirty

  "*/linux/arm64":
    zipname:    7za.linux.arm64.7z
  "*/darwin/arm64":
    zipname:    7za.darwin.arm64.7z
  "*/linux/x64":
    zipname:    7za.linux.x64.7z
  "*/darwin/x64":
    zipname:    7za.darwin.x64.7z
  "*/win/x64":
    zipname:    7za.x64.exe.7z
    bin_suffix: .exe
    file_suffix: zip
