homepage: https://golang.google.cn
license: MIT
rely: []

gh_url: https://raw.githubusercontent.com/static-build/p7zip/main/bin
gc_url: https://gitee.com/static-build/p7zip/raw/main/bin
url:
  _: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin:
  pzip: p7zip.%{osname}.%{osarch}%{bin_suffix}
  7z: p7zip.%{osname}.%{osarch}%{bin_suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: 1.6-dirty

  latest/*:
    version: 1.6-dirty

  "*/linux/arm64":
    zipname:    p7zip.linux.arm64.7z
  "*/darwin/arm64":
    zipname:    p7zip.darwin.arm64.7z
  "*/linux/x64":
    zipname:    p7zip.linux.x64.7z
  "*/darwin/x64":
    zipname:    p7zip.darwin.x64.7z
  "*/win/x64":
    zipname:    p7zip.x64.exe.7z
    bin_suffix: .exe
