homepage: https://github.com/oracle/visualvm/releases
license: Apache License
rely: []
_os: "%{os}"
_arch: "%{arch}"
file_suffix: zip
url:
  internet: "https://github.com/oracle/visualvm/releases/download/%{version}/visualvm_215.zip"
  cn: "https://github.com/oracle/visualvm/releases/download/%{version}/visualvm_215.zip"
unpack_way: unpack_copy_to_target_dir

xbin:
  visualvm: bin/visualvm

rule:
  /*:
    version: stable

  stable/*:
    version: "2.1.5"

  latest/*:
    version: "2.1.5"

  "*/linux/arm64":


  "*/darwin/arm64":


  "*/linux/x64":


  "*/darwin/x64":


  "*/win/x64":
    xbin:
      visualvm: bin/visualvm.exe

