homepage: https://github.com/denoland/deno/
license: MIT
rely: []
_os: "%{os}"
_arch: "%{arch}"
hook:
  install: install.sh
url:
    _: https://github.com/denoland/deno/releases/download/%{version}/deno-%{_arch}-%{_os}.%{file_suffix}
    cn: https://github.com/denoland/deno/releases/download/%{version}/deno-%{_arch}-%{_os}.%{file_suffix}
xbin:
  deno: deno

file_suffix: zip

rule:
  /*:
    version: v1.22.0
  v*/linux/x64:
    _arch: x86_64
    _os: unknown-linux-gnu
