homepage: https://github.com/denoland/deno/
license: MIT
rely: []

hook:
  pre-install: ""
  post-install: post-install.sh

rule:
  v*.linux-aarch64:
    url:
      _: https://github.com/denoland/deno/releases/download/v%{version}/deno-linux-aarh64.zip
      cn: https://github.com/denoland/deno/releases/download/v%{version}/deno-linux-aarh64.zip
  v*.darwin/arm64:
    url:
      _: https://golang.google.cn/dl/deno%{version}.darwin/arm64.tar.gz
      cn: https://golang.google.cn/dl/deno%{version}.darwin/arm64.tar.gz
  v*.linux/x64:
    url:
      _: https://github.com/denoland/deno/releases/download/v%{version}/deno-%{arch}-%{os}.zip
      cn: ""
  v*.darwin/x64:
    url:
      _: https://github.com/denoland/deno/releases/download/v%{version}/deno-%{arch}-%{os}.zip
      cn: ""
  v*.win/x64:
    url:
      _: https://github.com/denoland/deno/releases/download/v{version}/deno-%{arch}-%{os}.zip
      cn: ""
xbin:
  denobin: deno%{bin_suffix}
  a123: deno%{bin_suffix}
  a1234: deno%{bin_suffix}

