homepage: https://golang.google.cn
license: MIT
rely: []
bin:
  nmap: nmap/nmap.${osarch}.${osname}
  nping: nmap/nmap.${osarch}.${osname}
const:
  github_source: https://raw.githubusercontent.com/static-build/nmap/main/bin
  gitee_source: https://gitee.com/static-build/nmap/raw/main/bin
url:
  _: '%{github_source}/nmap.%{os}.%{arch}.7z'
  cn: '%{gitee_source}/nmap.%{os}.%{arch}.7z'
os-arch:
  linux-arm64:
  darwin-arm64:
  linux-x64:
  darwin-x64:
  win-x64:
    url:
      _: '%{github_source}/nmap.x64.exe.7z'
      cn: '%{gitee_source}/nmap.x64.exe.7z'
    bin:
      nmap: nmap/nmap.x64.win.exe
  win-arm64:
    url:
      _: '%{github_source}/nmap.arm64.exe.7z'
      cn: '%{gitee_source}/nmap.arm64.exe.7z'
    bin:
      nmap: nmap/nmap.arm64.win.exe
