homepage: https://golang.google.cn
license: MIT
rely: []

gh_url: https://raw.githubusercontent.com/static-build/nmap/main/bin
gc_url: https://gitee.com/static-build/nmap/raw/main/bin
file_suffix: 7z
static-build: nmap/nmap
url:
  _: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin: nmap.%{os}.%{arch}%{bin_suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: 7.92

  latest/*:
    version: 7.92

  "*/linux/arm64":
    zipname:    nmap.linux.arm64.7z
  "*/darwin/arm64":
    zipname:    nmap.darwin.arm64.7z
  "*/linux/x64":
    zipname:    nmap.linux.x64.7z
  "*/darwin/x64":
    zipname:    nmap.darwin.x64.7z
  "*/win/x64":
    zipname:    nmap.win.x64.exe.7z
    bin_suffix: .exe

