homepage: https://github.com/michael-simons/neo4j-migrations/releases
license: Apache License
rely: []
_os: "%{os}"
_arch: "%{arch}"
file_suffix: zip
url:
  internet: "https://github.com/michael-simons/neo4j-migrations/releases/download/%{version}/neo4j-migrations-%{version}-%{_os}-%{_arch}.zip"
  cn: "https://github.com/michael-simons/neo4j-migrations/releases/download/%{version}/neo4j-migrations-%{version}-%{_os}-%{_arch}.zip"
unpack_way: unpack_copy_to_target_dir

xbin:
  neo4j_migrations: bin/neo4j_migrations

rule:
  /*:
    version: stable

  stable/*:
    version: 2.2.2

  latest/*:
    version: 2.2.2

  "*/linux/arm64":
    _arch: aarch_64

  "*/darwin/arm64":
    _os: osx
    _arch: aarch_64

  "*/linux/x64":
    _arch: x86_64

  "*/darwin/x64":
    _os: osx
    _arch: x86_64

  "*/win/x64":
    _os: windows
    _arch: x86_64

