homepage: https://gitee.com/organizations/static-build/projects
license: MIT
rely: []
gh_url: https://github.com/x-cmd-build/smartmontools/releases/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/smartmontools/-/releases/%{version}/downloads
file_suffix: 7z
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin: smartctl.%{os}.%{arch}%{bin_suffix}
hook:
  activate: activate.sh
  deactivate: deactivate.sh
rule:
  /*:
    version: stable

  stable/*:
    version: v0.0.0

  latest/*:
    version: v0.0.0

  "*/linux/arm64":
    zipname:    smartctl.linux.arm64.7z
  "*/darwin/arm64":
    zipname:    smartctl.darwin.arm64.7z
  "*/linux/x64":
    zipname:    smartctl.linux.x64.7z
  "*/darwin/x64":
    zipname:    smartctl.darwin.x64.7z
  "*/win/x64":
    zipname:    smartctl.win.x64.exe.7z
    bin_suffix: .exe