homepage: https://gitee.com/organizations/static-build/projects
license: MIT
rely: []
gh_url: https://raw.githubusercontent.com/static-build/smartmontools/main/smartmontools/%{version}
gc_url: https://gitee.com/static-build/smartmontools/raw/main/smartmontools/%{version}
file_suffix: 7z
static-build: smartmontools/smartctl
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin: smartctl.%{os}.%{arch}%{bin_suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: 7.2

  latest/*:
    version: 7.2

  "*/linux/arm64":
    zipname:    smartctl.linux.arm64.7z
  "*/darwin/arm64":
    zipname:    smartctl.darwin.arm64.7z
  "*/linux/x64":
    zipname:    smartctl.linux.x64.7z
  "*/darwin/x64":
    zipname:    smartctl.darwin.x64.7z
  "*/win/x64":
    zipname:    smartctl.win.x64.exe.7z
    bin_suffix: .exe