homepage: https://gitee.com/organizations/static-build/projects
license: MIT
rely: []

gh_url: https://github.com/x-cmd-build/mosquitto/releases/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/mosquitto/-/releases/%{version}/downloads
file_suffix: 7z
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin:
  mosquitto: mosquitto%{bin_suffix}
  mqtt: mosquitto%{bin_suffix}
  mosquitto_passwd: mosquitto_passwd%{bin_suffix}
  mosquitto_pub: mosquitto_pub%{bin_suffix}
  mosquitto_rr: mosquitto_rr%{bin_suffix}
  mosquitto_sub: mosquitto_sub%{bin_suffix}
  mosquitto_ctrl: mosquitto_ctrl%{bin_suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: v0.0.0

  latest/*:
    version: v0.0.0

  "*/linux/arm64":
    zipname:    mosquitto.linux.arm64.7z
  "*/darwin/arm64":
    zipname:    mosquitto.darwin.arm64.7z
  "*/linux/x64":
    zipname:    mosquitto.linux.x64.7z
  "*/darwin/x64":
    zipname:    mosquitto.darwin.x64.7z
  "*/win/x64":
    zipname:    mosquitto.win.x64.exe.7z
    bin_suffix: .exe
