license: MIT
rely: []
file_suffix: tar.gz
url:
  _: "https://mirrors.tuna.tsinghua.edu.cn/julia-releases/bin/%{_os}/%{_arch}/%{version}/julia-%{version}-%{_osarch}.%{file_suffix}"
  cn: "https://mirrors.tuna.tsinghua.edu.cn/julia-releases/bin/%{_os}/%{_arch}/%{version}/julia-%{version}-%{_osarch}.%{file_suffix}"

xbin: bin/julia

_os: "%{os}"
_arch: "%{arch}"
unpack_way: unpack_copy_to_target_dir

rule:
  /*:
    version: latest

  latest/*:
    version: 1.8
  1.8/*:
    version: 1.8.0-rc1


  "*/linux/x64":
    _osarch: linux-x86_64

  "*/linux/x86":
    _osarch: linux-i686


  "*/linux/arm64":
    version: 0.6.0-rc1
    _osarch: linux-arm


    "*/linux/armv7l":
    version: 1.7.0-rc1
    _osarch: linux-armv7l


  "*/darwin/arm64":
    _os: mac
    _osarch: macaarch64

  "*/darwin/x64":
    _os: mac
    _osarch: mac64


  "*/win/x64":
    _osarch: win64
    file_suffix: tar.gz
    xbin: bin/julia.exe


  "*/win/x32":
    _osarch: win32
    file_suffix: tar.gz
    xbin: bin/julia.exe

