license: MIT
rely: []
file_suffix: tar.gz
url:
  _: "https://mirrors.tuna.tsinghua.edu.cn/julia-releases/bin/%{os}/%{arch}/%{version}/julia-%{version}-latest-%{_osarch}.%{file_suffix}"
  cn: "https://mirrors.tuna.tsinghua.edu.cn/julia-releases/bin/%{os}/%{arch}/%{version}/julia-%{version}-latest-%{_osarch}.%{file_suffix}"

xbin: bin/julia

_os: "%{os}"
_arch: "%{arch}"

rule:
  /*:
    version: latest

  latest/*:
    version: 1.8


  "*/linux/x64":
    _osarch: linux-x86_64
  "*/linux/x86":
    _osarch: linux-i686
  "*/linux/arm64":
    version: 0.6
    _osarch: linux-arm
    "*/linux/armv7l":
    version: 1.7
    _osarch: linux-armv7l

  "*/mac/arm64":
    _osarch: macaarch64
  "*/mac/x64":
    _osarch: mac64

  "*/win/x64":
    _osarch: win64
    file_suffix: exe
  "*/win/x32":
    _osarch: win32
    file_suffix: exe



