homepage: https://golang.google.cn
license: MIT
rely: []

gh_url: https://raw.githubusercontent.com/static-build/nmap/main/bin
gc_url: https://gitee.com/static-build/nmap/raw/main/bin
url:
  _: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin: traceroute.%{osname}.%{osarch}%{bin_suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: v0.10.1

  latest/*:
    version: v0.10.1

  "*/linux/arm64":
    zipname:    traceroute.linux.arm64.7z
  "*/darwin/arm64":
    zipname:    traceroute.darwin.arm64.7z
  "*/linux/x64":
    zipname:    traceroute.linux.x64.7z
  "*/darwin/x64":
    zipname:    traceroute.darwin.x64.7z
  "*/win/x64":
    zipname:    traceroute.x64.exe.7z
    bin:
      ffplay: .exe
