homepage: https://gitee.com/organizations/static-build/projects
license: MIT
rely: []

gh_url: https://raw.githubusercontent.com/static-build/nmap/main/traceroute/%{version}
gc_url: https://gitee.com/static-build/nmap/raw/main/traceroute/%{version}
file_suffix: 7z
static-build: traceroute/traceroute
url:
  _: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin: traceroute.%{os}.%{arch}%{bin_suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: 5.0.1

  latest/*:
    version: 5.0.1

  "*/linux/arm64":
    zipname:    traceroute.linux.arm64.7z
  "*/darwin/arm64":
    zipname:    traceroute.darwin.arm64.7z
  "*/linux/x64":
    zipname:    traceroute.linux.x64.7z
  "*/darwin/x64":
    zipname:    traceroute.darwin.x64.7z
  "*/win/x64":
    zipname:    traceroute.win.x64.exe.7z
    bin_suffix: .exe
