homepage: https://gitee.com/organizations/static-build/projects
license: MIT
rely: []

gh_url: https://github.com/x-cmd-build/kube-capacity/releases/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/kube-capacity/-/releases/%{version}/downloads
file_suffix: tar.xz
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin:
  kube-capacity: kube-capacity%{bin_suffix}


rule:
  /*:
    version: stable

  stable/*:
    version: v0.0.0

  latest/*:
    version: v0.0.0


  "*/darwin/x64":
    zipname:    kube-capacity_v0.7.4_darwin_x86_64.tar.xz
  "*/darwin/arm64":
    zipname:    kube-capacity_v0.7.4_darwin_arm64.tar.xz
  "*/linux/x64":
    zipname:    kube-capacity_v0.7.4_linux_x86_64.tar.xz
  "*/linux/arm64":
    zipname:    kube-capacity_v0.7.4_linux_arm64.tar.xz
  "*/win/x64":
    zipname:    kube-capacity_v0.7.4_windows_x86_64.tar.xz
    bin_suffix: .exe