homepage: https://api.sdkman.io/2/candidates/kotlin/LINUX64/versions/all
license: MIT
rely: []
const:
github_source: https://github.com/JetBrains/kotlin/releases/download
file_suffix: tar.gz
_os: "%{os}"
_arch: "%{arch}"
url:
  internet: '%{github_source}/v%{version}/kotlin-%{_os}-%{_arch}-%{version}.%{file_suffix}'
  cn: '%{github_source}/v%{version}/kotlin-%{_os}-%{_arch}-%{version}.%{file_suffix}'
xbin:
  kotlin: kotlin%{bin_suffix}
hook:
  activate: activate.sh
  deactivate: deactivate.sh

unpack_way: unpack_copy_to_target_dir

rule:
  /*:
    version: stable

  stable/*:
    version: 1.6.21

  "*/linux/x64":
    _os: native-linux
    _arch: x86_64

  "*/linux/arm64":
    _os: native-linux
    _arch: x86_64

  "*/win/x64":
    _os: native-windows
    _arch: x86_64
    file_suffix: zip

  "*/darwin/arm64":
    _os: native-macos
    _arch: aarch64

  "*/darwin/x64":
    _os: native-macos
    _arch: x86_64


