homepage: https://github.com/jreleaser/jreleaser/wiki/Release-early-access
license: Apache License
rely: []
_os: "%{os}"
_arch: "%{arch}"
file_suffix: zip
url:
  internet: "https://github.com/jreleaser/jreleaser/releases/download/v%{version}/jreleaser-standalone-%{version}-%{_os}-%{_arch}.zip"
  cn: "https://github.com/jreleaser/jreleaser/releases/download/v%{version}/jreleaser-standalone-%{version}-%{_os}-%{_arch}.zip"
unpack_way: unpack_copy_to_target_dir
xbin:
  jreleaser: bin/jreleaser
rule:
  /*:
    version: stable

  stable/*:
    version: 1.5.1

  latest/*:
    version: 1.5.1

  "*/linux/arm64":
    _arch: aarch64

  "*/darwin/arm64":
    _os: osx
    _arch: aarch64

  "*/linux/x64":
    _os: linux_musl
    _arch: x86_64

  "*/darwin/x64":
    _os: osx
    _arch: x86_64

  "*/win/x64":
    _os: windowns
    _arch: x86_64




