homepage: https://gitee.com/organizations/static-build/projects
license: MIT

gh_url: https://github.com/x-cmd-build/exa/releases/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/exa/-/releases/%{version}/downloads
file_suffix: 7z
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin:
  exa: exa.%{os}.%{arch}%{bin_suffix}
  ls: exa.%{os}.%{arch}%{bin_suffix}
  ll: exa.%{os}.%{arch}%{bin_suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: v0.10.1

  latest/*:
    version: v0.10.1

  "*/linux/arm64":
    zipname:    exa.linux.arm64.7z
  "*/darwin/arm64":
    zipname:    exa.darwin.arm64.7z
  "*/linux/x64":
    zipname:    exa.linux.x64.7z
  "*/darwin/x64":
    zipname:    exa.darwin.x64.7z
  "*/win/x64":
    zipname:    exa.win.x64.exe.7z
    bin_suffix: .exe
    file_suffix: zip
