homepage: https://golang.google.cn
license: MIT

gh_url: https://raw.githubusercontent.com/static-build/exa/main/bin
gc_url: https://gitee.com/static-build/exa/raw/main/bin
static-build: exa/exa
file_suffix: 7z
url:
  _: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin:
  exa: exa.%{osname}.%{osarch}%{bin_suffix}
  ll: exa.%{osname}.%{osarch}%{bin_suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: v0.10.1

  latest/*:
    version: v0.10.1

  "*/linux/arm64":
    zipname:    exa.linux.arm64.7z
  "*/darwin/arm64":
    zipname:    exa.darwin.arm64.7z
  "*/linux/x64":
    zipname:    exa.linux.x64.7z
  "*/darwin/x64":
    zipname:    exa.darwin.x64.7z
  "*/win/x64":
    zipname:    exa.x64.exe.7z
    bin_suffix: .exe
    file_suffix: zip
