homepage: https://golang.google.cn
license: MIT
rely: []

bin:
  ffplay: exa/exa.${osarch}.${osname}

gh_url: https://raw.githubusercontent.com/static-build/exa/main/bin
gc_url: https://gitee.com/static-build/exa/raw/main/bin
url:
  _: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

rule:
  /*:
    version: stable

  stable/*:
    version: v0.10.1

  latest/*:
    version: v0.10.1

  "*/linux/arm64":
    zipname:    exa.linux.arm64.7z
  "*/darwin/arm64":
    zipname:    exa.darwin.arm64.7z
  "*/linux/x64":
    zipname:    exa.linux.x64.7z
  "*/darwin/x64":
    zipname:    exa.darwin.x64.7z
  "*/win/x64":
    zipname:    exa.x64.exe.7z
    bin:
      ffplay: exa/exa.%{osarch}.%{osname}.exe
