homepage: https://golang.google.cn
license: MIT
rely: []

gh_url: https://github.com/x-cmd-build/bat/releases/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/bat/-/releases/%{version}/downloads
file_suffix: 7z
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin:
  bat: bat.%{os}.%{arch}%{bin_suffix}
  cat: bat.%{os}.%{arch}%{bin_suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: 0.18.2

  latest/*:
    version: 0.18.2

  "*/linux/arm64":
    zipname:    bat.linux.arm64.7z
  "*/darwin/arm64":
    zipname:    bat.darwin.arm64.7z
  "*/linux/x64":
    zipname:    bat.linux.x64.7z
  "*/darwin/x64":
    zipname:    bat.darwin.x64.7z
  "*/win/x64":
    zipname:    bat.win.x64.exe.7z
    bin_suffix: .exe