homepage: https://gitee.com/organizations/static-build/projects
license: MIT
rely: []

gh_url: https://github.com/x-cmd-build/releases/gitleaks/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/gitleaks/-/releases/%{version}/downloads
file_suffix: tar.xz
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin:
  gitleaks: gitleaks%{bin_suffix}


rule:
  /*:
    version: stable

  stable/*:
    version: v0.0.0

  latest/*:
    version: v0.0.0



  "*/darwin/arm64":
    zipname:    gitleaks_8.16.2_darwin_arm64.tar.xz
  "*/darwin/x64":
    zipname:    gitleaks_8.16.2_darwin_x64.tar.xz
  "*/linux/x64":
    zipname:    gitleaks_8.16.2_linux_x64.tar.xz
  "*/linux/arm64":
    zipname:    gitleaks_8.16.2_linux_arm64.tar.xz
  "*/win/x64":
    zipname:    gitleaks_8.16.2_windows_x64.tar.xz
    bin_suffix: .exe