homepage: https://github.com/manikmagar/mulefd
license: Apache License
rely: []
_os: "%{os}"
_arch: "%{arch}"
file_suffix: zip
url:
  internet: "https://github.com/manikmagar/mulefd/releases/download/v%{version}/mulefd-%{version}.zip"
  cn: "https://github.com/manikmagar/mulefd/releases/download/v%{version}/mulefd-%{version}.zip"
unpack_way: unpack_copy_to_target_dir

xbin:
  mulefd: bin/mulefd

rule:
  /*:
    version: stable

  stable/*:
    version: 0.11.0
  latest/*:
    version: 0.11.0

  "*/linux/arm64":


  "*/darwin/arm64":


  "*/linux/x64":


  "*/darwin/x64":


  "*/win/x64":
  

