homepage: https://golang.google.cn
license: MIT
rely: []

gh_url: https://github.com/x-cmd-build/pandoc/releases/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/pandoc/-/releases/%{version}/downloads
file_suffix: tar.xz
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"
unpack_way: unpack_copy_to_target_dir
xbin:
  pandoc: "bin/pandoc%{bin_suffix}"

rule:
  /*:
    version: stable

  stable/*:
    version: v0.0.0

  latest/*:
    version: v0.0.0

  "*/linux/arm64":
    zipname:    pandoc-3.1.2-linux-arm64.tar.xz
  "*/darwin/arm64":
    zipname:    pandoc-3.1.2-arm64-macOS.tar.xz
  "*/linux/x64":
    zipname:    pandoc-3.1.2-linux-amd64.tar.xz
  "*/darwin/x64":
    zipname:    pandoc-3.1.2-x86_64-macOS.tar.xz
  "*/win/x64":
    xbin:
      pandoc: "pandoc%{bin_suffix}"
    zipname:    pandoc-3.1.2-windows-x86_64.tar.xz
    bin_suffix: .exe
