homepage: https://github.com/mybatis/migrations/releases
license: Apache License
rely: []
_os: "%{os}"
_arch: "%{arch}"
file_suffix: zip
url:
  internet: "https://github.com/mybatis/migrations/releases/download/mybatis-migrations-%{version}/mybatis-migrations-%{version}-bundle.zip"
  cn: "https://github.com/mybatis/migrations/releases/download/mybatis-migrations-%{version}/mybatis-migrations-%{version}-bundle.zip"
unpack_way: unpack_copy_to_target_dir

xbin:
  mybatis_migrations: bin/migrate
  migrate: bin/migrate

rule:
  /*:
    version: stable

  stable/*:
    version: 3.3.11

  latest/*:
    version: 3.3.11

  "*/linux/arm64":


  "*/darwin/arm64":


  "*/linux/x64":


  "*/darwin/x64":


  "*/win/x64":


