homepage: https://gitee.com/organizations/static-build/projects
license: MIT

gum_url: https://github.com/x-cmd-build/gum/releases/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/gum/-/releases/%{version}/downloads
file_suffix: tar.gz
url:
  internet: "%{gum_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"
xbin:
  gum: gum%{bin_suffix}
hook:
  activate: activate.sh
rule:
  /*:
    version: stable

  stable/*:
    version: v0.0.0

  latest/*:
    version: v0.0.0

  "*/linux/arm64":
    zipname:    gum_0.10.0_Linux_arm64.tar.gz

  "*/darwin/arm64":
    zipname:    gum_0.10.0_Darwin_arm64.tar.gz

  "*/linux/x64":
    zipname:    gum_0.10.0_Linux_x86_64.tar.gz

  "*/darwin/x64":
    zipname:    gum_0.10.0_Darwin_x86_64.tar.gz

  "*/win/x64":
    zipname:    gum_0.10.0_Windows_x86_64.zip
    bin_suffix: .exe
    file_suffix: zip
