homepage: https://github.com/quarkusio/quarkus
license: Apache License
rely: []
_os: "%{os}"
_arch: "%{arch}"
file_suffix: zip
url:
  internet: "https://github.com/quarkusio/quarkus/releases/download/%{version}/quarkus-cli-%{version}.zip"
  cn: "https://github.com/quarkusio/quarkus/releases/download/%{version}/quarkus-cli-%{version}.zip"
unpack_way: unpack_copy_to_target_dir

xbin:
  quarkus: bin/quarkus

rule:
  /*:
    version: stable

  stable/*:
    version: "2.16.6.Final"

  latest/*:
    version: "2.16.6.Final"

  "*/linux/arm64":


  "*/darwin/arm64":


  "*/linux/x64":


  "*/darwin/x64":


  "*/win/x64":


