homepage: https://gitee.com/organizations/static-build/projects
license: MIT

gh_url: https://github.com/x-cmd-build/rg/releases/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/rg/-/releases/%{version}/downloads
file_suffix: tar.gz
unpack_way: unpack_copy_to_target_dir
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin: rg%{bin_suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: 13.0.0

  latest/*:
    version: 13.0.0

  "*/linux/arm64":
    zipname:    ripgrep-%{version}-x86_64-unknown-linux-musl.tar.gz
  "*/darwin/arm64":
    zipname:    ripgrep-%{version}-x86_64-apple-darwin.tar.gz
  "*/linux/x64":
    zipname:    ripgrep-%{version}-x86_64-unknown-linux-musl.tar.gz
  "*/darwin/x64":
    zipname:    ripgrep-%{version}-x86_64-apple-darwin.tar.gz
  "*/win/x64":
    zipname:    ripgrep-%{version}-x86_64-pc-windows-gnu.zip
    file_suffix: zip
    bin_suffix: .exe
