homepage: https://gitee.com/organizations/static-build/projects
license: MIT
rely: []

gh_url: https://github.com/x-cmd-build/upx/releases/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/qrencode/-/releases/%{version}/downloads
file_suffix: tar.xz
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin:
  upx: upx{bin_suffix}


rule:
  /*:
    version: stable

  stable/*:
    version: v0.0.0

  latest/*:
    version: v0.0.0

  "*/linux/x64":
    zipname:    upx-4.0.2-amd64_linux.tar.xz
  "*/linux/arm64":
    zipname:    upx-4.0.2-arm64_linux.tar.xz
  "*/win/x64":
    zipname:    upx-4.0.2-win64.zip
    file_suffix: zip
    bin_suffix: .exe