homepage: https://golang.google.cn
license: MIT
rely: []

gh_url: https://github.com/x-cmd-build/bwrap/releases/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/bwrap/-/releases/%{version}/downloads
file_suffix: 7z
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin:
  bwrap: bwrap.%{os}.%{arch}%{bin_suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: v0.7.0

  latest/*:
    version: v0.7.0

  "*/linux/arm64":
    zipname:    bwrap.linux.arm64.7z
  "*/linux/x64":
    zipname:    bwrap.linux.x64.7z
