homepage: https://gitee.com/organizations/static-build/projects
license: MIT
rely: []

gh_url: https://raw.githubusercontent.com/static-build/bandwhich/main/bandwhich/%{version}
gc_url: https://gitee.com/static-build/bandwhich/raw/main/bandwhich/%{version}
file_suffix: 7z
static-build: bandwhich/bandwhich
url:
  _: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin: bandwhich.%{os}.%{arch}%{bin_suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: 0.20.0

  latest/*:
    version: 0.20.0

  "*/linux/arm64":
    zipname:    bandwhich.linux.arm64.7z
  "*/darwin/arm64":
    zipname:    bandwhich.darwin.arm64.7z
  "*/linux/x64":
    zipname:    bandwhich.linux.x64.7z
  "*/darwin/x64":
    zipname:    bandwhich.darwin.x64.7z
  "*/win/x64":
    zipname:    bandwhich.win.x64.exe.7z
    bin_suffix: .exe