homepage: https://gitee.com/organizations/static-build/projects
license: MIT
rely: []
_os: "%{os}"

gh_url: https://github.com/x-cmd-build/kube-linter/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/kube-linter/-/releases/%{version}/downloads
file_suffix: tar.xz
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin:
  kube-linter: kube-linter-%{_os}


rule:
  /*:
    version: stable

  stable/*:
    version: v0.0.0

  latest/*:
    version: v0.0.0

  "*/darwin/x64":
    zipname:    kube-linter-darwin.tar.xz
  "*/darwin/arm64":
    zipname:    kube-linter-darwin.tar.xz
  "*/linux/x64":
    zipname:    kube-linter-linux.tar.xz
    _arch: amd64
  "*/linux/arm64":
    zipname:    kube-linter-linux.tar.xz
  "*/win/x64":
    zipname:    kube-linter.tar.xz
    xbin:
      kube-linter: kube-linter
    bin_suffix: .exe