homepage: https://github.com/kcctl/kcctl/releases/tag/v1.0.0.Beta3
license: Apache License
rely: []
_os: "%{os}"
_arch: "%{arch}"
file_suffix: zip
url:
  internet: "https://github.com/kcctl/kcctl/releases/download/v1.0.0.Beta3/kcctl-1.0.0.Beta3-linux-x86_64.zip"
  cn: "https://dlcdn.apache.org/karaf/%{version}/apache-karaf-%{version}.tar.gz"
unpack_way: unpack_copy_to_target_dir
xbin:
  kcctl: bin/kcctl
rule:
  /*:
    version: stable

  stable/*:
    version: 4.4.3

  latest/*:
    version: 4.4.3

  "*/linux/arm64":


  "*/darwin/arm64":


  "*/linux/x64":


  "*/darwin/x64":


  "*/win/x64":
    xbin:
      kcctl: bin/kcctl.exe




