homepage: https://github.com/agorapulse/pierrot/releases
license: Apache License
rely: []
_os: "%{os}"
_arch: "%{arch}"
file_suffix: zip
url:
  internet: "https://github.com/agorapulse/pierrot/releases/download/%{version}/pierrot-%{_os}-%{_arch}-v%{version}.zip"
  cn: "https://github.com/agorapulse/pierrot/releases/download/%{version}/pierrot-%{_os}-%{_arch}-v%{version}.zip"
unpack_way: unpack_copy_to_target_dir

xbin:
  pierrot: bin/pierrot

rule:
  /*:
    version: stable

  stable/*:
    version: 2.2.2

  latest/*:
    version: 2.2.2

  "*/linux/arm64":
    _arch: amd64

  "*/darwin/arm64":
    _os: osx
    _arch: amd64

  "*/linux/x64":
    _arch: amd64

  "*/darwin/x64":
    _os: osx
    _arch: amd64

  "*/win/x64":
    _os: windows
    _arch: amd64

