homepage: https://golang.google.cn/dl/
license: MIT
rely: []
file_suffix: tar.gz
_os: "%{os}"
_arch: "%{arch}"
url:
  _: "https://go.dev/dl/go%{version}.%{_os}-%{_arch}.%{file_suffix}"
  cn: "https://golang.google.cn/dl/go%{version}.%{_os}-%{_arch}.%{file_suffix}"
xbin:
  go: bin/gofmt

hook:
  activate: activate.sh
  deactivate: deactivate.sh
  install: "install.sh"

rule:
  /*:
    version: latest

  latest/*:
    version: 1.18.2

  "*/win/x64":
    _os: windows
    _arch: 386
    file_suffix: zip


  "*/linux/x64":
    _arch: 386


  "*/darwin/x*":
    _arch: "amd64"