homepage: https://github.com/IoT-Technology/IoT-Toolkit/releases/
license: Apache License
rely: []
_os: "%{os}"
_arch: "%{arch}"
file_suffix: zip
url:
  internet: "https://github.com/IoT-Technology/IoT-Toolkit/releases/download/%{version}/toolkit-%{version}-%{_os}-%{_arch}.zip"
  cn: "https://github.com/IoT-Technology/IoT-Toolkit/releases/download/%{version}/toolkit-%{version}-%{_os}-%{_arch}.zip"
unpack_way: unpack_copy_to_target_dir

xbin:
  toolkit: bin/toolkit

rule:
  /*:
    version: stable

  stable/*:
    version: "0.6.5"

  latest/*:
    version: "0.6.5"

  "*/linux/arm64":
    _arch : aarch_64

  "*/darwin/arm64":
    _os: osx
    _arch: x86_64

  "*/linux/x64":
    _arch: x86_64

  "*/darwin/x64":
    _arch: x86_64
    _os: osx

  "*/win/x64":
    _arch: x86_64
    _os: windows
