homepage: https://rust-lang.org
license: MIT
rely: []
file_suffix: tar.gz
rust_source: https://static.rust-lang.org/dist
cn_source: "https://static.rust-lang.org/dist"
_os: "%{os}"
_arch: "%{arch}"
url:
  _: '%{rust_source}/rust-%{version}-%{file_suffix}'
  cn: '%{cn_source}/rust-%{version}-%{_arch}-%{_os}.%{file_suffix}'

xbin:
    rustc: bin/rustc
    rust: bin/rustc

hook:
  pre-install: ""
  install: install.sh

rule:

  /*:
    version: 1.60.0

  "*/darwin/arm64":
    _arch: aarch64
    _os: apple-darwin

  "*/linux/x64":
    _arch: x86_64
    _os: unknown-linux-gnu
    file_suffix: tar.gz

  win/x64:
    file_suffix: zip

  win-arm64:
    file_suffix: aarch64-pc-windows-msvc.zip


