homepage: https://e.gitee.com/lteam18/repos/static-build/proot/tree/main/v/0.1.0
license: MIT
rely: []

gh_url: https://github.com/proot-me/proot-rs/releases/download/%{version}/proot-rs-%{version}-%{_arch}-%{_os}.%{file_suffix}
gt_url: https://gitee.com/static-build/proot/raw/main/v%2F0.1.0%2Fproot-rs-%{version}-%{_arch}-%{_os}.%{file_suffix}
file_suffix: tar.gz

url:
  en: "%{gh_url}"
  cn: "%{gt_url}"

xbin:
  proot: proot-rs

rule:
  /*:
    version: stable

  stable/*:
    version: v0.1.0

  latest/*:
    version: v0.1.0

  "*/linux/amd64":
    _os: unknown-linux-gnu
    _arch: aarch64
    zipname:    proot-rs.linux.amd64.tar.gz
  "*/linux/arm64":
    _os: linux-androideabi
    _arch: arm
    zipname:    proot-rs.linux.arm.tar.gz
  "*/linux/x64":
    _os: unknown-linux-gnu
    _arch: x86_64
    zipname:    proot-rs.linux.x64.tar.gz

