homepage: https://e.gitee.com/lteam18/repos/static-build/proot/tree/main/v/0.1.0
license: MIT
rely: []

gh_url: https://github.com/x-cmd-build/proot/releases/download/%{version}
gt_url: https://gitcode.net/x-cmd-build/proot/-/releases/%{version}/downloads
file_suffix: tar.gz
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gt_url}/%{zipname}"

xbin:
  proot: proot-rs
hook:
  activate: activate.sh
  deactivate: deactivate.sh
rule:
  /*:
    version: stable

  stable/*:
    version: v0.0.0

  latest/*:
    version: v0.0.0

  "*/linux/arm64":
    zipname:    proot-rs-v0.1.0-aarch64-unknown-linux-gnu.tar.gz
  "*/linux/x64":
    zipname:    proot-rs-v0.1.0-x86_64-linux-android.tar.gz

