homepage: https://e.gitee.com/lteam18/repos/static-build/proot/tree/main/v/0.1.0
license: MIT
rely: []

gh_url: https://github.com/x-cmd-build/procs/releases/download/%{version}/proot-rs-%{version}-%{_arch}-%{_os}.%{file_suffix}
gt_url: https://gitcode.net/x-cmd-build/procs/-/releases/%{version}/downloads/proot-rs-%{version}-%{_arch}-%{_os}.%{file_suffix}
file_suffix: tar.gz
url:
  internet: "%{gh_url}"
  cn: "%{gt_url}"

xbin:
  proot: proot-rs

rule:
  /*:
    version: stable

  stable/*:
    version: v0.0.0

  latest/*:
    version: v0.0.0

  "*/linux/amd64":
    _os: unknown-linux-gnu
    _arch: aarch64
    zipname:    proot-rs.linux.amd64.tar.gz
  "*/linux/arm64":
    _os: unknown-linux-gnu
    _arch: aarch64
    zipname:    proot-rs.linux.arm.tar.gz
  "*/linux/x64":
    _os: unknown-linux-gnu
    _arch: x86_64
    zipname:    proot-rs.linux.x64.tar.gz

