homepage: https://golang.google.cn
license: MIT
rely: []

bin:
  ffplay: dust/dust.%{osarch}.%{osname}

xbin:
  dust: dust.%{bin_suffix}

gh_url: https://raw.githubusercontent.com/static-build/dust/main/bin
gc_url: https://gitee.com/static-build/dust/raw/main/bin
url:
  _: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

rule:
  /*:
    version: stable

  stable/*:
    version: 0.6.0

  latest/*:
    version: 0.6.0

  "*/linux/arm64":
    zipname:    dust.linux.arm64.7z
  "*/darwin/arm64":
    zipname:    dust.darwin.arm64.7z
  "*/linux/x64":
    zipname:    dust.linux.x64.7z
  "*/darwin/x64":
    zipname:    dust.darwin.x64.7z
  "*/win/x64":
    zipname:    dust.x64.exe.7z
    bin_suffix: .exe
