homepage: https://gitee.com/organizations/static-build/projects
license: MIT
rely: []

gh_url: https://github.com/x-cmd-build/dust/releases/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/dust/-/releases/%{version}/downloads
file_suffix: 7z
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin:
  du: dust.%{os}.%{arch}%{bin_suffix}
  dust: dust.%{os}.%{arch}%{bin_suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: 0.6.0

  latest/*:
    version: 0.6.0

  "*/linux/arm64":
    zipname:    dust.linux.arm64.7z
  "*/darwin/arm64":
    zipname:    dust.darwin.arm64.7z
  "*/linux/x64":
    zipname:    dust.linux.x64.7z
  "*/darwin/x64":
    zipname:    dust.darwin.x64.7z
  "*/win/x64":
    zipname:    dust.win.x64.exe.7z
    bin_suffix: .exe
