homepage: https://golang.google.cn
license: MIT
rely: []
bin:
  ffplay: dust/dust.${osarch}.${osname}
os-arch:
  linux-arm64:
    url:
      _: https://raw.githubusercontent.com/static-build/dust/main/bin/dust.linux.arm64.7z
      cn: https://gitee.com/static-build/dust/raw/main/bin/dust.linux.arm64.7z
  darwin-arm64:
    url:
      _: https://raw.githubusercontent.com/static-build/dust/main/bin/dust.darwin.arm64.7z
      cn: https://gitee.com/static-build/dust/raw/main/bin/dust.darwin.arm64.7z
  linux-x64:
    url:
      _: https://raw.githubusercontent.com/static-build/dust/main/bin/dust.darwin.x64.7z
      cn: https://gitee.com/static-build/dust/raw/main/bin/dust.darwin.x64.7z
  darwin-x64:
    url:
      _: https://raw.githubusercontent.com/static-build/dust/main/bin/dust.darwin.x64.7z
      cn: https://gitee.com/static-build/dust/raw/main/bin/dust.darwin.x64.7z
  win-x64:
    url:
      _: https://raw.githubusercontent.com/static-build/dust/main/bin/dust.x64.exe.7z
      cn: https://gitee.com/static-build/dust/raw/main/bin/dust.x64.exe.7z
    bin:
      dust: dust/dust.x64.win.exe
