homepage: https://gitee.com/organizations/static-build/projects
license: MIT
rely: []

gh_url: https://raw.githubusercontent.com/static-build/nmap/main/nping/%{version}
gc_url: https://gitee.com/static-build/nmap/raw/main/nping/%{version}
file_suffix: 7z
static-build: nmap/nping
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin: nping.%{os}.%{arch}%{bin_suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: 7.92

  latest/*:
    version: 7.92

  "*/linux/arm64":
    zipname:    nping.linux.arm64.7z
  "*/darwin/arm64":
    zipname:    nping.darwin.arm64.7z
  "*/linux/x64":
    zipname:    nping.linux.x64.7z
  "*/darwin/x64":
    zipname:    nping.darwin.x64.7z

