homepage: https://golang.google.cn
license: MIT
rely: []

gh_url: https://raw.githubusercontent.com/static-build/nmap/main/bin
gc_url: https://gitee.com/static-build/nmap/raw/main/bin
file_suffix: 7z
static-build: nmap/nping
url:
  _: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin: nping.%{os}.%{arch}%{bin_:suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: v0.10.1

  latest/*:
    version: v0.10.1

  "*/linux/arm64":
    zipname:    nping.linux.arm64.7z
  "*/darwin/arm64":
    zipname:    nping.darwin.arm64.7z
  "*/linux/x64":
    zipname:    nping.linux.x64.7z
  "*/darwin/x64":
    zipname:    nping.darwin.x64.7z
  "*/win/x64":
    zipname:    nping.x64.exe.7z
    bin_suffix: .exe
