homepage: https://gitee.com/organizations/static-build/projects
license: MIT
rely: []
_os: "%{os}"
_arch: "%{arch}"
gh_url: https://github.com/x-cmd-build/k3d/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/k3d/-/releases/%{version}/downloads
file_suffix: tar.xz
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin:
  k3d: k3d-%{_os}-%{_arch}


rule:
  /*:
    version: stable

  stable/*:
    version: v0.0.0

  latest/*:
    version: v0.0.0

  "*/darwin/x64":
    zipname:    k3d-darwin-amd64.tar.xz
  "*/darwin/arm64":
    zipname:    k3d-darwin-arm64.tar.xz
  "*/linux/x64":
    zipname:    k3d-linux-amd64.tar.xz
    _arch: amd64
  "*/linux/arm64":
    zipname:    k3d-linux-arm64.tar.xz
  "*/win/x64":
    zipname:    k3d-windows-amd64.tar.xz
    xbin:
      k3d: k3d-windows-amd64
    bin_suffix: .exe