homepage: https://github.com/kordamp/pomchecker/releases
license: Apache License
rely: []
_os: "%{os}"
_arch: "%{arch}"
file_suffix: zip
url:
  internet: "https://github.com/kordamp/pomchecker/releases/download/v%{version}/pomchecker-%{version}.zip"
  cn: "https://github.com/kordamp/pomchecker/releases/download/v%{version}/pomchecker-%{version}.zip"
unpack_way: unpack_copy_to_target_dir

xbin:
  pomchecker: bin/pomchecker

rule:
  /*:
    version: stable

  stable/*:
    version: 1.9.0

  latest/*:
    version: 1.9.0

  "*/linux/arm64":


  "*/darwin/arm64":


  "*/linux/x64":


  "*/darwin/x64":


  "*/win/x64":


