homepage: https://github.com/kordamp/pomchecker/releases
license: Apache License
rely: []
_os: "%{os}"
_arch: "%{arch}"
file_suffix: zip
url:
  internet: "https://github.com/kordamp/pomchecker/releases/download/v%{version}/pomchecker-%{version}.zip"
  cn: "https://github.com/kordamp/pomchecker/releases/download/v%{version}/pomchecker-%{version}.zip"
unpack_way: unpack_copy_to_target_dir

xbin:
  pomchecker: bin/pomchecker

rule:
  /*:
    version: stable

  stable/*:
    version: 2.2.2

  latest/*:
    version: 2.2.2

  "*/linux/arm64":
    _arch: amd64

  "*/darwin/arm64":
    _os: osx
    _arch: amd64

  "*/linux/x64":
    _arch: amd64

  "*/darwin/x64":
    _os: osx
    _arch: amd64

  "*/win/x64":
    _os: windows
    _arch: amd64

