homepage: https://golang.google.cn
license: MIT
rely: []

bin:
  ffplay: jq/jq.${osarch}.${osname}

xbin: jq.%{osarch}.%{osname}%{bin_suffix}

gh_url: https://raw.githubusercontent.com/static-build/jq/main/bin/%{version}
gc_url: https://gitee.com/static-build/jq/raw/main/bin/%{version}
url:
  _: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

rule:
  /*:
    version: stable

  stable/*:
    version: 1.6-dirty

  latest/*:
    version: 1.6-dirty

  "*/linux/arm64":
    zipname:    jq.linux.arm64.7z
  "*/darwin/arm64":
    zipname:    jq.darwin.arm64.7z
  "*/linux/x64":
    zipname:    jq.linux.x64.7z
  "*/darwin/x64":
    zipname:    jq.darwin.x64.7z
  "*/win/x64":
    zipname:    jq.x64.exe.7z
    bin_suffix: .exe
