homepage: https://gitee.com/organizations/static-build/projects
license: MIT
rely: []

gh_url: https://github.com/x-cmd-build/jq/releases/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/jq/-/releases/%{version}/downloads
file_suffix: 7z

url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin: jq.%{os}.%{arch}%{bin_suffix}


rule:
  /*:
    version: stable

  stable/*:
    version: 1.6-dirty

  latest/*:
    version: 1.6-dirty

  "*/linux/arm64":
    zipname:    jq.linux.arm64.7z
  "*/darwin/arm64":
    zipname:    jq.darwin.arm64.7z
  "*/linux/x64":
    zipname:    jq.linux.x64.7z
  "*/darwin/x64":
    zipname:    jq.darwin.x64.7z
  "*/win/x64":
    zipname:    jq.win.x64.exe.7z
    bin_suffix: .exe
