homepage: https://github.com/cbmarcum/skeletal
license: Apache License
rely: []
_os: "%{os}"
_arch: "%{arch}"
file_suffix: zip
url:
  internet: "https://github.com/cbmarcum/skeletal/releases/download/v%{version}/skeletal-%{version}.zip"
  cn: "https://github.com/cbmarcum/skeletal/releases/download/v%{version}/skeletal-%{version}.zip"
unpack_way: unpack_copy_to_target_dir

xbin:
  skeletal: bin/skeletal

rule:
  /*:
    version: stable

  stable/*:
    version: "0.15.0"

  latest/*:
    version: "0.15.0"

  "*/linux/arm64":


  "*/darwin/arm64":


  "*/linux/x64":


  "*/darwin/x64":


  "*/win/x64":


