homepage: https://golang.google.cn
license: MIT
rely: []

gh_url: https://raw.githubusercontent.com/static-build/gost/main/gost/%{version}
gc_url: https://gitee.com/static-build/gost/raw/main/gost/%{version}
file_suffix: tar.gz
static-build: gost/gost
url:
  en: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin:
  gost: gost%{bin_suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: v3.0.0-rc6

  latest/*:
    version: v3.0.0-rc6

  "*/linux/arm64":
    zipname:    gost_3.0.0-rc6_linux_arm64.tar.gz
  "*/darwin/arm64":
    zipname:    gost_3.0.0-rc6_darwin_arm64.tar.gz
  "*/linux/x64":
    zipname:    gost_3.0.0-rc6_linux_amd64.tar.gz
  "*/darwin/x64":
    zipname:    gost_3.0.0-rc6_darwin_amd64.tar.gz
  "*/win/x64":
    zipname:    gost_3.0.0-rc6_windows_amd64.zip
    bin_suffix: .exe
    file_suffix: zip
