homepage: https://golang.google.cn
license: MIT
rely: []

bin:
  ffplay: fzf/fzf.${osarch}.${osname}

gh_url: https://github.com/junegunn/fzf/releases/download/%{version}
gc_url: https://download.fastgit.org/junegunn/fzf/releases/download/%{version}
url:
  _: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

rule:

  "*/linux/arm64":
    zipname:    fzf-%{version}-linux_arm64.tar.gz
  "*/darwin/arm64":
    zipname:    fzf-%{version}-darwin_arm64.zip
  "*/linux/x64":
    zipname:    fzf-%{version}-linux_amd64.tar.gz
  "*/darwin/x64":
    zipname:    fzf-%{version}-darwin_amd64.zip
  "*/win/x64":
    zipname:    fzf-%{version}-windows_amd64.zip
    bin:
      ffplay: fzf/fzf.%{osarch}.%{osname}.exe

  default/*:
    version: latest

  latest/*:
    version: v0.10.1
