homepage: https://golang.google.cn
license: MIT


gh_url: https://github.com/junegunn/fzf/releases/download/%{version}
gc_url: https://download.fastgit.org/junegunn/fzf/releases/download/%{version}
url:
  _: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin: fzf.%{osname}.%{osarch}%{bin_suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: v0.10.1

  latest/*:
    version: v0.10.1

  "*/linux/arm64":
    zipname:    fzf-%{version}-linux_arm64.tar.gz
  "*/darwin/arm64":
    zipname:    fzf-%{version}-darwin_arm64.zip
  "*/linux/x64":
    zipname:    fzf-%{version}-linux_amd64.tar.gz
  "*/darwin/x64":
    zipname:    fzf-%{version}-darwin_amd64.zip
  "*/win/x64":
    zipname:    fzf-%{version}-windows_amd64.zip
    bin_suffix: .exe
