homepage: https://gitee.com/organizations/static-build/projects
license: MIT


gh_url: https://github.com/x-cmd-build/fzf/releases/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/fzf/-/releases/%{version}/downloads
file_suffix: zip
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin: fzf%{bin_suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: 0.30.0

  latest/*:
    version: 0.30.0

  "*/linux/arm64":
    zipname:    fzf-%{version}-linux_arm64.tar.gz
    file_suffix: tar.gz
  "*/darwin/arm64":
    zipname:    fzf-%{version}-darwin_arm64.zip
  "*/linux/x64":
    zipname:    fzf-%{version}-linux_amd64.tar.gz
    file_suffix: tar.gz
  "*/darwin/x64":
    zipname:    fzf-%{version}-darwin_amd64.zip
  "*/win/x64":
    zipname:    fzf-%{version}-windows_amd64.zip
    bin_suffix: .exe
