homepage: https://gitee.com/organizations/static-build/projects
license: MIT

gh_url: https://get.helm.sh
gc_url: https://repo.huaweicloud.com/helm/%{version}
file_suffix: tar.gz
url:
  _: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin: helm%{bin_suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: v3.9.0

  latest/*:
    version: v3.9.0

  "*/linux/arm64":
    zipname:    helm-v3.9.0-linux-arm64.tar.gz
  "*/darwin/arm64":
    zipname:    helm-v3.9.0-darwin-arm64.tar.gz
  "*/linux/x64":
    zipname:    helm-v3.9.0-linux-amd64.tar.gz
  "*/darwin/x64":
    zipname:    helm-v3.9.0-darwin-amd64.tar.gz
  "*/win/x64":
    zipname:    helm-v3.9.0-windows-amd64.zip
    file_suffix: zip
    bin_suffix: .exe