homepage: https://gitee.com/organizations/static-build/projects
license: MIT

gh_url: https://github.com/x-cmd-build/gh/releases/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/gh/-/releases/%{version}/downloads
file_suffix: tar.gz
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"
unpack_way: unpack_copy_to_target_dir
xbin:
  ghcli: gh
hook:
  activate: activate.sh
  deactivate: deactivate.sh
rule:
  /*:
    version: stable

  stable/*:
    version: v0.0.0

  latest/*:
    version: v0.0.0

  "*/linux/arm64":
    zipname:    gh_2.25.1_linux_arm64.tar.gz
    xbin:       gh_2.25.1_linux_arm64/bin/gh

  "*/darwin/arm64":
    zipname:    gh_2.25.1_macOS_arm64.tar.gz
    xbin:       gh_2.25.1_macOS_arm64/bin/gh

  "*/linux/x64":
    zipname:    gh_2.25.1_linux_amd64.tar.gz
    xbin:       gh_2.25.1_linux_amd64/bin/gh

  "*/darwin/x64":
    zipname:    gh_2.25.1_macOS_amd64.tar.gz
    xbin:       gh_2.25.1_macOS_amd64/bin/gh

  "*/win/x64":
    zipname:    gh_2.25.1_windows_amd64.zip
    xbin:       bin/gh.exe
    file_suffix: zip
