homepage: https://gitee.com/organizations/static-build/projects
license: MIT

gh_url: https://github.com/cli/cli/releases/download/%{version}
gc_url: https://download.fastgit.org/cli/cli/releases/download/%{version}
file_suffix: tar.gz
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin:
  gh: gh

rule:
  /*:
    version: stable

  stable/*:
    version: v2.25.1

  latest/*:
    version: v2.25.1

  "*/linux/arm64":
    zipname:    gh_2.25.1_linux_arm64.tar.gz
    xbin:       gh_2.25.1_linux_arm64/bin/gh

  "*/darwin/arm64":
    zipname:    gh_2.25.1_macOS_amd64.tar.gz
    xbin:       gh_2.25.1_macOS_amd64/bin/gh

  "*/linux/x64":
    zipname:    gh_2.25.1_linux_amd64.tar.gz
    xbin:       gh_2.25.1_linux_amd64/bin/gh

  "*/darwin/x64":
    zipname:    gh_2.25.1_macOS_amd64.tar.gz
    xbin:       gh_2.25.1_macOS_amd64/bin/gh

  "*/win/x64":
    zipname:    gh_2.25.1_windows_amd64.zip
    xbin:       bin/gh.exe
    file_suffix: zip
