homepage: https://gitee.com/organizations/static-build/projects
license: MIT
rely: []

gh_url: https://github.com/x-cmd-build/duf/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/duf/-/releases/%{version}/downloads
file_suffix: tar.xz
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin:
  duf: duf%{bin_suffix}


rule:
  /*:
    version: stable

  stable/*:
    version: v0.0.0

  latest/*:
    version: v0.0.0

  "*/darwin/arm64":
    zipname:    duf_0.8.1_Darwin_arm64.tar.xz
  "*/darwin/x64":
    zipname:    duf_0.8.1_Darwin_x86_64.tar.xz
  "*/linux/x64":
    zipname:    duf_0.8.1_linux_x86_64.tar.xz
  "*/linux/arm64":
    zipname:    duf_0.8.1_linux_arm64.tar.xz
  "*/win/x64":
    zipname:    duf_0.8.1_Windows_x86_64.tar.xz

    bin_suffix: .exe
