homepage: https://www.terraform.io/downloads
license: MIT

gh_url: https://releases.hashicorp.com/terraform/%{version}
gc_url: https://gitcode.net/x-bash/terraform/-/raw/main/%{version}
file_suffix: zip
url:
  en: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"
xbin: terraform%{bin_suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: 1.2.2

  latest/*:
    version: 1.2.2
  "*/linux/arm64":
    zipname:    terraform_%{version}_linux_arm64.zip
  "*/darwin/arm64":
    zipname:    terraform_%{version}_darwin_arm64.zip
  "*/linux/x64":
    zipname:    terraform_%{version}_linux_amd64.zip
  "*/darwin/x64":
    zipname:    terraform_%{version}_darwin_amd64.zip
  "*/win/x64":
    zipname:    terraform_%{version}_windows_amd64.zip
    bin_suffix: .exe