homepage: https://www.terraform.io/downloads
license: MIT

gh_url: https://github.com/x-cmd-build/terraform/releases/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/terraform/-/releases/%{version}/downloads
file_suffix: zip
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"
xbin: terraform%{bin_suffix}
hook:
  activate: activate.sh
  deactivate: deactivate.sh
rule:
  /*:
    version: stable

  stable/*:
    version: v0.0.0

  latest/*:
    version: v0.0.0
  "*/linux/arm64":
    zipname:    terraform_1.2.2_linux_arm64.zip
  "*/darwin/arm64":
    zipname:    terraform_1.2.2_darwin_arm64.zip
  "*/linux/x64":
    zipname:    terraform_1.2.2_linux_amd64.zip
  "*/darwin/x64":
    zipname:    terraform_1.2.2_darwin_amd64.zip
  "*/win/x64":
    zipname:    terraform_1.2.2_windows_amd64.zip
    bin_suffix: .exe