homepage: https://gitee.com/organizations/static-build/projects
license: MIT
rely: []

gh_url: https://github.com/x-cmd-build/goreleaser/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/goreleaser/-/releases/%{version}/downloads
file_suffix: tar.xz
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin:
  goreleaser: goreleaser.%{os}.%{arch}%{bin_suffix}


rule:
  /*:
    version: stable

  stable/*:
    version: v0.0.0

  latest/*:
    version: v0.0.0

  "*/darwin/arm64":
    zipname:    goreleaser_Darwin_arm64.tar.xz
  "*/darwin/x64":
    zipname:    goreleaser_Darwin_x86_64.tar.xz
  "*/linux/arm64":
    zipname:    goreleaser_Linux_arm64.tar.xz
  "*/linux/x64":
    zipname:    goreleaser_Linux_x86_64.tar.xz
  "*/win/x64":
    zipname:    goreleaser_Windows_x86_64.tar.xz
    bin_suffix: .exe
