homepage: https://gitee.com/organizations/static-build/projects
license: MIT
rely: []
os-arch:
  linux/arm64:
    url:
      _: https://gitee.com/organizations/static-build/projects/dl/go%{version}.linux/arm64.tar.gz
      cn: https://gomirros.org/dl/go%{version}.linux/arm64.tar.gz
  darwin/arm64:
    url:
      _: https://gitee.com/organizations/static-build/projects/dl/go%{version}.darwin/arm64.tar.gz
      cn: https://gomirros.org/dl/go%{version}.darwin/arm64.tar.gz
  linux/x64:
    url:
      _: https://gitee.com/organizations/static-build/projects/dl/go%{version}.linux-amd64.tar.gz
      cn: https://gomirros.org/dl/go%{version}.linux-amd64.tar.gz
  darwin/x64:
    url:
      _: https://gitee.com/organizations/static-build/projects/dl/go%{version}.darwin-amd64.tar.gz
      cn: https://gomirros.org/dl/go%{version}.darwin-amd64.tar.gz
  win/x64:
    url:
      _: https://gitee.com/organizations/static-build/projects/dl/go%{version}.windows-amd64.zip
      cn: https://gomirros.org/dl/go%{version}.windows-amd64.zip
xbin:
  ruby: ruby%{bin_suffix}