homepage: https://rubygems.org/gems/asciidoctor/versions/2.0.18
license: Apache License
rely: []

file_suffix: tar.gz
url:
  internet: "https://rubygems.org/downloads/asciidoctor-%{version}.gem"
  cn: "https://rubygems.org/downloads/asciidoctor-%{version}.gem"

xbin:
  asciidoctorj: asciidoctorj.%{os}.%{arch}
unpack_way: non_unpack
rule:
  /*:
    version: stable

  stable/*:
    version: 2.0.18

  latest/*:
    version: 2.0.18

  "*/linux/arm64":

  "*/darwin/arm64":

  "*/linux/x64":

  "*/darwin/x64":

  "*/win/x64":


