homepage: https://gitee.com/organizations/static-build/projects
license: MIT
rely: []

gh_url: https://github.com/x-cmd-build/kind/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/kind/-/releases/%{version}/downloads
file_suffix: tar.xz
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin:
  kind: kind%{bin_suffix}


rule:
  /*:
    version: stable

  stable/*:
    version: v0.0.0

  latest/*:
    version: v0.0.0


  "*/darwin/x64":
    zipname:    kind-darwin-amd64.tar.xz
  "*/darwin/arm64":
    zipname:    kind-darwin-arm64.tar.xz
  "*/linux/x64":
    zipname:    kind-linux-amd64.tar.xz
  "*/linux/arm64":
    zipname:    kind-linux-arm64.tar.xz
  "*/win/x64":
    zipname:    kind-windows-amd64.tar.xz