homepage: https://github.com/kscripting/kscript
license: Apache License
rely: []
_os: "%{os}"
_arch: "%{arch}"
file_suffix: zip
url:
  internet: "https://github.com/kscripting/kscript/releases/download/v4.2.1/kscript-4.2.1-bin.zip"
  cn: "https://github.com/kscripting/kscript/releases/download/v4.2.1/kscript-4.2.1-bin.zip"
unpack_way: unpack_copy_to_target_dir

xbin:
  kscript: bin/kscript
rule:
  /*:
    version: stable

  stable/*:
    version: v4.2.1

  latest/*:
    version: v4.2.1

  "*/linux/arm64":


  "*/darwin/arm64":


  "*/linux/x64":


  "*/darwin/x64":


  "*/win/x64":






