homepage: https://gitee.com/organizations/static-build/projects
license: MIT
rely: []

gh_url: https://github.com/x-cmd-build/openssl/releases/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/openssl/-/releases/%{version}/downloads
file_suffix: 7z
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin:
  ssl: openssl.%{os}.%{arch}%{bin_suffix}
  openssl: openssl.%{os}.%{arch}%{bin_suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: 3.0.0

  latest/*:
    version: 3.0.0

  "*/linux/arm64":
    zipname:    openssl.linux.arm64.7z
  "*/darwin/arm64":
    zipname:    openssl.darwin.arm64.7z
  "*/linux/x64":
    zipname:    openssl.linux.x64.7z
  "*/darwin/x64":
    zipname:    openssl.darwin.x64.7z
  "*/win/x64":
    zipname:    openssl.win.x64.exe.7z
    bin_suffix: .exe

