homepage: https://gitee.com/organizations/static-build/projects
license: MIT
rely: []

gh_url: https://github.com/x-cmd-build/difftastic/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/difftastic/-/releases/%{version}/downloads
file_suffix: tar.xz
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin:
  difft: difft%{bin_suffix}


rule:
  /*:
    version: stable

  stable/*:
    version: v0.0.0

  latest/*:
    version: v0.0.0


  "*/darwin/x64":
    zipname:    difft-x86_64-apple-darwin.tar.xz
  "*/linux/x64":
    zipname:    difft-x86_64-unknown-linux-gnu.tar.xz
  "*/win/x64":
    zipname:    difft-x86_64-pc-windows-msvc.tar.xz
    bin_suffix: .exe
