homepage: https://gitee.com/organizations/static-build/projects
license: MIT
rely: []

gh_url: https://github.com/x-cmd-build/helix/releases/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/helix/-/releases/%{version}/downloads
file_suffix: tar.xz
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

unpack_way: unpack_copy_to_target_dir

xbin:
  helix: hx
  hx: hx


rule:
  /*:
    version: stable

  stable/*:
    version: v0.0.0

  latest/*:
    version: v0.0.0

  "*/darwin/arm64":
    zipname:    helix-23.03-aarch64-macos.tar.xz

  "*/darwin/x64":
    zipname:    helix-23.03-x86_64-macos.tar.xz

  "*/linux/x64":
    zipname:    helix-23.03-x86_64-linux.tar.xz
  "*/linux/arm64":
    zipname:    helix-23.03-aarch64-linux.tar.xz

  "*/win/x64":
    zipname:    helix-23.03-x86_64-windows.tar.xz
    xbin: hx.exe
    bin_suffix: .exe