homepage: https://github.com/kobo/gaiden/releases
license: Apache License
rely: []
_os: "%{os}"
_arch: "%{arch}"
file_suffix: zip
url:
  internet: "https://services.gradle.org/distributions/gradle-%{version}-bin.zip"
  cn: "https://services.gradle.org/distributions/gradle-%{version}-bin.zip"
unpack_way: unpack_copy_to_target_dir
xbin:
  gradle: bin/gradle
rule:
  /*:
    version: stable

  stable/*:
    version: v1.3

  latest/*:
    version: v1.3

  "*/linux/arm64":

  "*/darwin/arm64":

  "*/linux/x64":

  "*/darwin/x64":

  "*/win/x64":




