homepage: https://gitee.com/organizations/static-build/projects
license: MIT
rely: []

gh_url: https://github.com/x-cmd-build/ws4sqlite/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/ws4sqlite/-/releases/%{version}/downloads
file_suffix: tar.xz
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin:
  ws4sqlite: ws4sqlite%{bin_suffix}


rule:
  /*:
    version: stable

  stable/*:
    version: v0.0.0

  latest/*:
    version: v0.0.0


  "*/darwin/x64":
    zipname:    ws4sqlite-v0.14.1-darwin-amd64.tar.xz

  "*/darwin/arm64":
    zipname:    ws4sqlite-v0.14.1-darwin-arm64.tar.xz

  "*/linux/x64":
    zipname:    ws4sqlite-v0.14.1-linux-amd64.tar.xz
  "*/linux/arm64":
    zipname:    ws4sqlite-v0.14.1-linux-arm64.tar.xz
  "*/win/x64":
    zipname:    ws4sqlite-v0.14.1-win-amd64.tar.xz

    bin_suffix: .exe