homepage: https://gitee.com/organizations/static-build/projects
license: MIT
rely: []

gh_url: https://github.com/x-cmd-build/p7zip/releases/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/p7zip/-/releases/%{version}/downloads
file_suffix: 7z
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"
hook:
  install: install.sh
hook:
  activate: activate.sh
  deactivate: deactivate
  install: install.sh
xbin:
  p7zip: 7za.%{os}.%{arch}%{bin_suffix}
  7za: 7za.%{os}.%{arch}%{bin_suffix}
  7z: 7za.%{os}.%{arch}%{bin_suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: v0.0.0

  latest/*:
    version: v0.0.0

  "*/linux/arm64":
    zipname:    7za.linux.arm64.7z
  "*/darwin/arm64":
    zipname:    7za.darwin.arm64.7z
  "*/linux/x64":
    zipname:    7za.linux.x64.7z
  "*/darwin/x64":
    zipname:    7za.darwin.x64.7z
  "*/win/x64":
    zipname:    7za.win.x64.exe.7z
    bin_suffix: .exe

