homepage: https://gitee.com/organizations/static-build/projects
license: MIT
rely: []

gh_url: https://raw.githubusercontent.com/static-build/yq/main/yq/%{version}
gc_url: https://gitee.com/static-build/yq/raw/main/yq/%{version}
static-build: yq/yq
file_suffix: 7z
url:
  en: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin: yq.%{os}.%{arch}%{bin_suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: 4.15.1

  latest/*:
    version: 4.15.1

  "*/linux/arm64":
    zipname:    yq.linux.arm64.7z
  "*/darwin/arm64":
    zipname:    yq.darwin.arm64.7z
  "*/linux/x64":
    zipname:    yq.linux.x64.7z
  "*/darwin/x64":
    zipname:    yq.darwin.x64.7z
  "*/win/x64":
    zipname:    yq.win.x64.exe.7z
    bin_suffix: .exe
