homepage: https://gitee.com/organizations/static-build/projects
license: MIT

gh_url: https://github.com/x-cmd-build/fd/releases/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/fd/-/releases/%{version}/downloads
file_suffix: tar.gz
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin:
  fd: fd
  ff: fd

rule:
  /*:
    version: stable

  stable/*:
    version: v0.0.0

  latest/*:
    version: v0.0.0

  "*/linux/arm64":
    zipname:    fd-v8.3.2-arm-unknown-linux-musleabihf.tar.gz
    xbin:       fd-v8.3.2-arm-unknown-linux-musleabihf/fd

  "*/darwin/arm64":
    zipname:    fd-v8.3.2-x86_64-apple-darwin.tar.gz
    xbin:       fd-v8.3.2-x86_64-apple-darwin/fd

  "*/linux/x64":
    zipname:    fd-v8.3.2-x86_64-unknown-linux-musl.tar.gz
    xbin:       fd-v8.3.2-x86_64-unknown-linux-musl/fd

  "*/darwin/x64":
    zipname:    fd-v8.3.2-x86_64-apple-darwin.tar.gz
    xbin:       fd-v8.3.2-x86_64-apple-darwin/fd

  "*/win/x64":
    zipname:    fd-v8.3.2-x86_64-pc-windows-gnu.zip
    xbin:       fd-v8.3.2-x86_64-pc-windows-gnu/fd.exe
    file_suffix: zip
