homepage: https://gitee.com/organizations/static-build/projects
license: MIT

gh_url: https://github.com/sharkdp/fd/releases/download/%{version}
gc_url: https://download.fastgit.org/sharkdp/fd/releases/download/%{version}
file_suffix: tar.gz
url:
  _: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"
_os: "%{os}"
_arch: "%{arch}"

xbin:
  fd: fd-%{version}-%{_arch}-%{_os}/fd
  ff: fd-%{version}-%{_arch}-%{_os}/fd

rule:
  /*:
    version: stable

  stable/*:
    version: v8.3.2

  latest/*:
    version: v8.3.2

  "$app/$version/linux/arm64":
    zipname:    $app-v8.3.2-arm-unknown-linux-musleabihf.tar.gz
    _os: linux-musleabihf
    _arch: arm-unknown

  "*/darwin/arm64":
    zipname:    fd-v8.3.2-x86_64-apple-darwin.tar.gz
    xbin: xsssss

  "*/linux/x64":
    zipname:    fd-v8.3.2-x86_64-unknown-linux-musl.tar.gz
    _os: unknown-linux-musl
    _arch: x86_64

  "*/darwin/x64":
    zipname:    fd-v8.3.2-x86_64-apple-darwin.tar.gz
    _arch: x86_64
    _os: apple-darwin

  "*/win/x64":
    zipname:    fd-v8.3.2-x86_64-pc-windows-gnu.zip
    xbin: fd.exe
    file_suffix: zip
    _arch: x86_64
    _os: pc-windows-gnu
    xbin:
    fd: fd-%{version}-%{_arch}-%{_os}/fd
    ff: fd-%{version}-%{_arch}-%{_os}/fd
