homepage: https://golang.google.cn
license: MIT

https://github.com/sharkdp/fd/releases/download/v8.3.2/fd-v8.3.2-x86_64-pc-windows-gnu.zip
gh_url: https://github.com/sharkdp/fd/releases/download/%{version}
gc_url: https://download.fastgit.org/sharkdp/fd/releases/download/%{version}
file_suffix: tar.gz
url:
  _: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin: fzf.%{os}.%{arch}%{bin_suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: v8.3.2

  latest/*:
    version: v8.3.2

  "*/linux/arm64":
    zipname:    fd-v8.3.2-arm-unknown-linux-musleabihf.tar.gz
  "*/darwin/arm64":
    zipname:    fd-v8.3.2-x86_64-apple-darwin.tar.gz
  "*/linux/x64":
    zipname:    fd-v8.3.2-aarch64-unknown-linux-gnu.tar.gz
  "*/darwin/x64":
    zipname:    fd-v8.3.2-x86_64-apple-darwin.tar.gz
  "*/win/x64":
    zipname:    fd-v8.3.2-x86_64-pc-windows-gnu.zip
    file_suffix: zip
    bin_suffix: .exe
