homepage: https://gitee.com/organizations/static-build/projects
license: MIT
rely: []

gh_url: https://github.com/x-cmd-build/micro/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/micro/-/releases/%{version}/downloads
file_suffix: tar.xz
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

unpack_way: unpack_copy_to_target_dir

xbin:
  micro: micro%{bin_suffix}


rule:
  /*:
    version: stable

  stable/*:
    version: v0.0.0

  latest/*:
    version: v0.0.0

  "*/darwin/arm64":
    zipname:    micro-2.0.11-macos-arm64.tar.xz
  "*/darwin/x64":
    zipname:    micro-2.0.11-osx.tar.xz
  "*/linux/x64":
    zipname:    micro-2.0.11-linux64.tar.xz
  "*/linux/arm64":
    zipname:    micro-2.0.11-linux-arm64.tar.xz
  "*/win/x64":
    zipname:    micro-2.0.11-win64.tar.xz
    bin_suffix: .exe