homepage: https://gitee.com/organizations/static-build/projects
license: MIT
rely: []

gh_url: https://github.com/x-cmd-build/xsv/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/xsv/-/releases/%{version}/downloads
file_suffix: tar.gz
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin:
  xsv: xsv%{bin_suffix}


rule:
  /*:
    version: stable

  stable/*:
    version: v0.0.0

  latest/*:
    version: v0.0.0


  "*/linux/x64":
    zipname:    xsv-0.13.0-x86_64-unknown-linux-musl.tar.gz
  "*/darwin/x64":
    zipname:    xsv-0.13.0-x86_64-apple-darwin.tar.gz
  "*/win/x64":
    zipname:    xsv-0.13.0-x86_64-pc-windows-gnu.zip
    file_suffix: zip
    bin_suffix: .exe