homepage: https://golang.google.cn
license: MIT
rely: []

gh_url: https://github.com/x-cmd-build/sqlite3/releases/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/sqlite3/-/releases/%{version}/downloads
file_suffix: 7z

url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin: sqlite3.%{os}.%{arch}%{bin_suffix}
hook:
  activate: activate.sh
  deactivate: deactivate.sh
rule:
  /*:
    version: stable

  stable/*:
    version: v0.0.0

  latest/*:
    version: v0.0.0

  "*/linux/arm64":
    zipname:    sqlite3.linux.arm64.7z
  "*/darwin/arm64":
    zipname:    sqlite3.darwin.arm64.7z
  "*/linux/x64":
    zipname:    sqlite3.linux.x64.7z
  "*/darwin/x64":
    zipname:    sqlite3.darwin.x64.7z
  "*/win/x64":
    zipname:    sqlite3.win.x64.exe.7z
    bin_suffix: .exe