homepage: https://golang.google.cn
license: MIT
rely: []
bin:
  ffplay: ffmpeg/ffmpeg.${osarch}.${osname}

gh_url: https://raw.githubusercontent.com/static-build/ffmpeg/main/bin
gc_url: https://gitcode.net/x-bash/ffmpeg/-/raw/master/bin
url:
  _: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"
os-arch:
  linux-arm64:
    zipname:    ffmpeg.linux.arm64.7z
  darwin-arm64:
    zipname:    ffmpeg.darwin.arm64.7z
  linux-x64:
    zipname:    ffmpeg.linux.x64.7z
  darwin-x64:
    zipname:    ffmpeg.darwin.x64.7z
  win-x64:
    zipname:    ffmpeg.x64.exe.7z
    bin:
      ffplay: ffmpeg/ffmpeg.${osarch}.${osname}.exe
