homepage: https://golang.google.cn
license: MIT
rely: []

gh_url: https://raw.githubusercontent.com/static-build/ffmpeg/main/bin
gc_url: https://gitcode.net/x-bash/ffmpeg/-/raw/master/bin
static-build: ffmpeg/ffmpeg
file_suffix: 7z
url:
  _:
    - "%{gh_url}/%{zipname}"
    - "%{gc_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin: ffmpeg.%{os}.%{arch}%{bin_suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: N-105323-gdd17c86aa1-tessus

  latest/*:
    version: N-105323-gdd17c86aa1-tessus

  "*/linux/arm64":
    zipname:    ffmpeg.linux.arm64.7z
  "*/darwin/arm64":
    zipname:    ffmpeg.darwin.arm64.7z
  "*/linux/x64":
    zipname:    ffmpeg.linux.x64.7z
  "*/darwin/x64":
    zipname:    ffmpeg.darwin.x64.7z
  "*/win/x64":
    zipname:    ffmpeg.x64.exe.7z
    bin:
      ffplay: ffmpeg/ffmpeg.%{osarch}.%{osname}.exe

