homepage: https://gitee.com/organizations/static-build/projects
license: MIT
rely: []

gh_url: https://raw.githubusercontent.com/static-build/ffmpeg/main/ffmpeg/%{version}
gc_url: https://gitcode.net/x-bash/ffmpeg/-/raw/main/ffmpeg/%{version}
file_suffix: 7z

url:
  internet: "%{gc_url}/%{zipname}.%{file_suffix}"
  cn: "%{gc_url}/%{zipname}.%{file_suffix}"

xbin: ffmpeg.%{os}.%{arch}%{bin_suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: N-105323-gdd17c86aa1-tessus

  latest/*:
    version: N-105323-gdd17c86aa1-tessus

  "*/linux/arm64":
    zipname:    ffmpeg.linux.arm64
  "*/darwin/arm64":
    zipname:    ffmpeg.darwin.arm64
  "*/linux/x64":
    zipname:    ffmpeg.linux.x64
  "*/darwin/x64":
    zipname:    ffmpeg.darwin.x64
  "*/win/x64":
    zipname:    ffmpeg.win.x64.exe
    bin:
      ffplay: ffmpeg/ffmpeg.%{osarch}.%{osname}.exe

