homepage: https://golang.google.cn
license: MIT
rely: []

gh_url: https://raw.githubusercontent.com/static-build/qrencode/main/qrencode/%{version}
gc_url: https://gitee.com/static-build/qrencode/raw/main/qrencode/%{version}
file_suffix: 7z
static-build: qrencode/qrencode
url:
  _: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin:
  qrencode: qrencode.%{os}.%{arch}%{bin_suffix}
  qr: qrencode.%{os}.%{arch}%{bin_suffix}


rule:
  /*:
    version: stable

  stable/*:
    version: 16.02

  latest/*:
    version: 16.02

  "*/linux/arm64":
    zipname:    qrencode.linux.arm64.7z
  "*/darwin/arm64":
    zipname:    qrencode.darwin.arm64.7z
  "*/linux/x64":
    zipname:    qrencode.linux.x64.7z
  "*/darwin/x64":
    zipname:    qrencode.darwin.x64.7z
  "*/win/x64":
    zipname:    qrencode.win.x64.exe.7z
    bin_suffix: .exe

