homepage: https://sdkman.io/
license: MIT
rely: []
sdkman_url: https://api.sdkman.io/2/broker/download/java
injdk_url: https://d6.injdk.cn

file_suffix: tar.gz
_os: "%{os}"
_arch: "%{arch}"
url:
  internet: "%{sdkman_url}/%{version}/%{_os}%{_arch}"
  cn: "%{sdkman_url}/%{version}/%{_os}%{_arch}"

xbin:
  java: bin/javac
hook:
  install: install.sh
  activate: activate.sh
  deactivate: deactivate.sh

unpack_way: unpack_copy_to_target_dir

rule:

  /*:
    version: stable

  stable/*:
    version: 18.0.2-sem

  latest/*:
    version: 18.0.2-sem

  "*/win/*":
    _os: mingw64_nt_10

  "18*?/linux/x64":
    url:
      cn: https://d6.injdk.cn/openjdk/openjdk/18/openjdk-18_linux-x64_bin.tar.gz

  "18*?/linux/arm64":
    url:
      cn: https://d6.injdk.cn/openjdk/openjdk/18/openjdk-18_linux-aarch64_bin.tar.gz

  "18*?/darwin/arm64":
    url:
      cn: https://d6.injdk.cn/openjdk/openjdk/18/openjdk-18_macos-aarch64_bin.tar.gz

  "18*?/darwin/x64":
    url:
      cn: https://d6.injdk.cn/openjdk/openjdk/18/openjdk-18_macos-x64_bin.tar.gz

  "18*?/win/x64":
    url:
      cn: https://d6.injdk.cn/openjdk/openjdk/18/openjdk-18_windows-x64_bin.zip

  "17*?/linux/x64":
    url:
      cn: https://d6.injdk.cn/openjdk/openjdk/17/openjdk-17.0.1_linux-x64_bin.tar.gz

  "17*?/linux/arm64":
    url:
      cn: https://d6.injdk.cn/openjdk/openjdk/17/openjdk-17.0.1_linux-aarch64_bin.tar.gz

  "17*?/darwin/arm64":
    url:
      cn: https://d6.injdk.cn/openjdk/openjdk/17/openjdk-17.0.1_macos-aarch64_bin.tar.gz

  "17*?/darwin/x64":
    url:
      cn: https://d6.injdk.cn/openjdk/openjdk/17/openjdk-17.0.1_macos-x64_bin.tar.gz

  "17*?/win/x64":
    url:
      cn: https://d6.injdk.cn/openjdk/openjdk/17/openjdk-17.0.1_windows-x64_bin.zip

  "16*?/linux/x64":
    url:
      cn: https://d6.injdk.cn/openjdk/openjdk/16/openjdk-16.0.1_linux-x64_bin.tar.gz

  "16*?/darwin/x64":
    url:
      cn: https://d6.injdk.cn/openjdk/openjdk/16/openjdk-16.0.1_osx-x64_bin.tar.gz

  "16*?/win/x64":
    url:
      cn: https://d6.injdk.cn/openjdk/openjdk/16/openjdk-16.0.1_windows-x64_bin.zip

  "16*?/linux/arm64":
    cn: https://d6.injdk.cn/openjdk/openjdk/16/openjdk-16.0.1_linux-aarch64_bin.tar.gz

  "15*?/linux/x64":
    url:
      cn: https://d6.injdk.cn/openjdk/openjdk/15/openjdk-15.0.2_linux-x64_bin.tar.gz

  "15*?/darwin/x64":
    url:
      cn: https://d6.injdk.cn/openjdk/openjdk/15/openjdk-15.0.2_osx-x64_bin.tar.gz

  "15*?/win/x64":
    url:
      cn: https://d6.injdk.cn/openjdk/openjdk/15/openjdk-15.0.2_windows-x64_bin.zip

  "15*?/linux/arm64":
    url:
      cn: https://d6.injdk.cn/openjdk/openjdk/15/openjdk-15.0.2_linux-aarch64_bin.tar.gz

  "14*?/linux/x64":
    url:
      cn: https://d6.injdk.cn/openjdk/openjdk/14/openjdk-14.0.2_linux-x64_bin.tar.gz

  "14*?/win/x64":
    url:
      cn: https://d6.injdk.cn/openjdk/openjdk/14/openjdk-14.0.2_windows-x64_bin.zip

  "14*?/darwin/x64":
    url:
      cn: https://d6.injdk.cn/openjdk/openjdk/14/openjdk-14.0.2_osx-x64_bin.tar.gz






