homepage: https://sdkman.io/
license: MIT
rely: []
sdkman_url: https://api.sdkman.io/2/broker/download/java
file_suffix: tar.gz
url:
  _: "%{sdkman_url}/%{version}/%{os}%{arch}"
  cn: "%{sdkman_url}/%{version}/%{os}%{arch}"
xbin:
  java: bin/javac

  install: post-install.sh

rule:

  /*:
    version: stable

  stable/*:
    version: 18-open

  latest/*:
    version: openjdk-v8.3.2

  v*/linux/arm64:
  v*/darwin/arm64:
  v*/linux/x64:
  v*/darwin/x64:
  v*/mingw64_nt_10.0-x64:
    file_suffix: zip

