homepage: https://sdkman.io/
license: MIT
rely: []
os-arch:
  linux-arm64:
    url:
      _: https://api.sdkman.io/2/broker/download/java/{version}/%{os}%{arch}
  darwin-arm64:
    url:
      _: https://api.sdkman.io/2/broker/download/java/{version}/%{os}%{arch}
  linux-x64:
    url:
      _: https://api.sdkman.io/2/broker/download/java/{version}/%{os}%{arch}
  darwin-x64:
    url:
      _: https://api.sdkman.io/2/broker/download/java/{version}/%{os}%{arch}
  mingw64_nt_10.0-x64:
    url:
      _: https://api.sdkman.io/2/broker/download/java/{version}/%{os}%{arch}
version:
  "*-v18.*":
    hook:
      post-install: special.v18.sh
  "graal-v*":
    hook:
      post-install: graal.sh
  "openjdk-v*":
    hook:
      post-install: openjdk.sh
  "zulu-v*":
    hook:
      post-install: zulu.sh

