homepage: https://sdkman.io/
license: MIT
rely: []
sdkman_url: https://api.sdkman.io/2/broker/download/java
tsinghua_url: https://d6.injdk.cn/oraclejdk/%{version}/jdk-%{version}_windows-x64_bin.zip

file_suffix: tar.gz
_os: "%{os}"
_arch: "%{arch}"
url:
  _: "%{sdkman_url}/%{version}/%{_os}%{_arch}"
  cn: "%{sdkman_url}/%{version}/%{_os}%{_arch}"

xbin:
  java: bin/javac
hook:
  install: install.sh
  activate: activate.sh
  deactivate: deactivate.sh

unpack_way: unpack_copy_to_target_dir

rule:

  /*:
    version: stable

  stable/*:
    version: 18-open

  latest/*:
    version: openjdk-v8.3.2

  18/
