homepage: https://sdkman.io/
license: MIT
rely: []
sdkmam_url: https://api.sdkman.io/2/broker/download/java
url:
  _: "%{sdkman_url}/{version}/%{os}%{arch}"

hook:
  setup: env-init.sh
  install: . post-install.sh

rule:
  v*/linux-arm64:
  v*/darwin-arm64:
  v*/linux-x64:
  v*/darwin-x64:
  v*/mingw64_nt_10.0-x64:

  graal-v*:
    hook:
      install: graal.sh
  openjdk-v*:
    hook:
      install: openjdk.sh
  zulu-v*:
    hook:
      install: zulu.sh

  "*-v18.*":
    hook:
      install: special.v18.sh

