homepage: https://sdkman.io/
license: MIT
rely: []
sdkman_url: https://api.sdkman.io/2/broker/download/java
file_suffix: tar.gz
_os: "%{os}"
_arch: "%{arch}"
url:
  _: "%{sdkman_url}/%{version}/%{_os}%{_arch}"
  cn: "%{sdkman_url}/%{version}/%{_os}%{_arch}"
xbin:
  java: bin/javac

  install: post-install.sh

rule:

  /*:
    version: stable

  stable/*:
    version: 18-open

  latest/*:
    version: openjdk-v8.3.2

  "*/linux/arm64":
  "*/darwin/arm64":
  "*/linux/x64":
  "*/darwin/x64":

  "*/win/x64":
    file_suffix: zip
    _os: mingw64_nt_10


