homepage: https://sdkman.io/
license: MIT
rely: []
sdkman_url: https://api.sdkman.io/2/broker/download/java
injdk_url: https://d6.injdk.cn

file_suffix: tar.gz
_os: "%{os}"
_arch: "%{arch}"
url:
  en: "%{sdkman_url}/%{version}/%{_os}%{_arch}"
  cn: "%{sdkman_url}/%{version}/%{_os}%{_arch}"

xbin:
  java: bin/javac
hook:
  install: install.sh
  activate: activate.sh
  deactivate: deactivate.sh

unpack_way: unpack_copy_to_target_dir
file_suffix: tar.gz

rule:

  /*:
    version: stable

  stable/*:
    version: 18

  latest/*:
    version: openjdk-v8.3.2

  "*/darwin/x64":
    _os: macos

  "*/darwin/amd64":
    _os: macos
    _arch: aarch64

  "*/windows/*":
    _os: windows
    file_suffix: zip

  16/*/*:
    url:
      cn: https://d6.injdk.cn/oraclejdk/16/jdk-16.0.2_%{_os}-%{_arch}_bin.%{file_suffix}


  11.0.12/*/*:
    url:
      cn: https://d6.injdk.cn/oraclejdk/11/jdk-11.0.12_%{_os}-%{_arch}_bin.%{file_suffix}


  8/*/*:
    url:
      cn: https://d6.injdk.cn/oraclejdk/8/jdk-8u301-%{_os}-%{_arch}_bin.%{file_suffix}

  17/*/*:
    url:
      cn: https://d6.injdk.cn/oraclejdk/16/jdk-16.0.2_%{_os}-%{_arch}_bin.%{file_suffix}

  18/*/*:
    url:
      cn: https://d6.injdk.cn/oraclejdk/18/jdk-18_%{_os}-%{_arch}_bin.%{file_suffix}

  16/win/*:
    file_suffix: zip
    url:
      cn: https://d6.injdk.cn/openjdk/openjdk/16/openjdk-16.0.1_windows-x64_bin.%{file_suffix}


  11.0.12/win/*:
    file_suffix: zip
    url:
      cn: https://d6.injdk.cn/openjdk/openjdk/11/openjdk-11+28_windows-x64_bin.%{file_suffix}


  8/win/*:
    file_suffix: zip
    url:
      cn: https://d6.injdk.cn/openjdk/openjdk/8/openjdk-8u41-b04-windows-i586-14_jan_2020.%{file_suffix}

  17/win/*:
    file_suffix: zip
    url:
      cn: https://d6.injdk.cn/openjdk/openjdk/17/openjdk-17.0.1_windows-x64_bin.%{file_suffix}

  18/win/*:
    file_suffix: zip
    url:
      cn: https://d6.injdk.cn/openjdk/openjdk/18/openjdk-18_windows-x64_bin.%{file_suffix}

  16.0.2/darwin/amd64:
    _os: osx
    _arch: aarch64

  16*/darwin/x64:
    _os: osx

  11*/darwin/amd64:
    _os: osx
    _arch: aarch64

  11*/darwin/x64:
    _os: osx

  "*/linux/amd64":
    _arch: aarch64


  8*/darwin/amd64:
    _os: macos
    _arch: aarch64
    file_suffix: dmg

  18*/darwin/amd64:
    _os: macosx
    _arch: aarch64

  18*/darwin/arm64:
    _os: macos
    _arch: aarch64

  18*/darwin/x64:
    _os: macosx

