homepage: https://sdkman.io/
license: MIT
rely: []
sdkman_url: https://api.sdkman.io/2/broker/download/java
tsinghua_url: https://mirrors.tuna.tsinghua.edu.cn/Adoptium

file_suffix: tar.gz
_os: "%{os}"
_arch: "%{arch}"
url:
  _: "%{sdkman_url}/%{version}/%{_os}%{_arch}"
  cn: "%{sdkman_url}/%{version}/%{_os}%{_arch}"

xbin:
  java: bin/javac
hook:
  install: install.sh
  activate: activate.sh
  deactivate: deactivate.sh

unpack_way: unpack_copy_to_target_dir

rule:

  /*:
    version: stable

  stable/*:
    version: 18-open

  latest/*:
    version: openjdk-v8.3.2

  "*/linux/arm64":
  "*/darwin/arm64":
  "*/linux/x64":
  "*/darwin/x64":

  "*/win/x64":
    file_suffix: zip
    _os: mingw64_nt_10


  "8/win/*":
    _os: windows
    url:
      cn: "%{tsinghua_url}/%{version}/jdk/%{_arch}/%{_os}/OpenJDK%{version}U-jdk_{_arch}_{_os}_hotspot_8u322b06.%{file_suffix}"

  "8/linux/*":
    url:
      cn: "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/8/jdk/%{_arch}/linux/OpenJDK8U-jdk_%{_arch}_linux_openj9_linuxXL_8u282b08_openj9-0.24.0.tar.gz"

  "8/darwin/*":
    url:
      cn: "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/8/jdk/%{_arch}/mac/OpenJDK8U-jdk_%{_arch}_mac_openj9_macosXL_8u282b08_openj9-0.24.0.tar.gz"

  "9/win/*":
    url:
      cn: "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/9/jdk/%{_arch}/windows/OpenJDK9-OPENJ9_%{_arch}_Windows_jdk-9.0.4.12_openj9-0.9.0.zip"

  "9/linux/*":
    url:
      cn: "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/9/jdk/%{_arch}/linux/OpenJDK9-OPENJ9_%{_arch}_Linux_jdk-9.0.4.12_openj9-0.9.0.tar.gz"

  "9/darwin/*":
    url:
      cn: "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/9/jdk/%{_arch}/mac/OpenJDK9U-jdk_%{_arch}_mac_hotspot_9_181.tar.gz"


  "10/win/*":
    url:
      cn: "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/10/jdk/%{_arch}/windows/OpenJDK10-OPENJ9_%{_arch}_Windows_jdk-10.0.2.13_openj9-0.9.0.zip"

  "10/linux/*":
    url:
      cn: "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/10/jdk/%{_arch}/linux/OpenJDK10-OPENJ9_%{_arch}_Linux_jdk-10.0.2.13_openj9-0.9.0.tar.gz"

  "10/darwin/*":
    url:
      cn: "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/10/jdk/%{_arch}/mac/OpenJDK10U-jdk_%{_arch}_mac_hotspot_10.0.2_13.tar.gz"

  "11/win/*":
    url:
      cn: "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/11/jdk/%{_arch}/windows/OpenJDK11U-jdk_%{_arch}_windows_openj9_windowsXL_11.0.10_9_openj9-0.24.0.zip"

  "11/linux/*":
    url:
      cn: "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/11/jdk/%{_arch}/linux/OpenJDK11U-jdk_%{_arch}_linux_openj9_linuxXL_11.0.10_9_openj9-0.24.0.tar.gz"

  "11/darwin/*":
    url:
      cn: "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/11/jdk/%{_arch}/mac/OpenJDK11U-jdk_%{_arch}_mac_openj9_macosXL_11.0.10_9_openj9-0.24.0.tar.gz"

  "12/win/*":
    url:
      cn: "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/12/jdk/%{_arch}/windows/OpenJDK12U-jdk_%{_arch}_windows_openj9_12.0.2_10_openj9-0.15.1.zip"

  "12/linux/*":
    url:
      cn: "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/12/jdk/%{_arch}/linux/OpenJDK12U-jdk_%{_arch}_linux_openj9_12.0.2_10_openj9-0.15.1.tar.gz"

  "12/darwin/*":
    url:
      cn: "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/12/jdk/%{_arch}/mac/OpenJDK12U-jdk_%{_arch}_mac_openj9_12.0.2_10.3_openj9_0.15.1.tar.gz"

  "13/darwin/*":
    url:
      cn: "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/13/jdk/%{_arch}/mac/OpenJDK13U-jdk_%{_arch}_mac_openj9_13.0.2_8_openj9-0.18.0.tar.gz"

  "13/win/*":
    url:
      cn: "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/13/jdk/%{_arch}/windows/OpenJDK13U-jdk_%{_arch}_windows_openj9_13.0.2_8_openj9-0.18.0.zip"

  "13/linux/*":
    url:
      cn: "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/13/jdk/%{_arch}/linux/OpenJDK13U-jdk_%{_arch}_linux_openj9_13.0.2_8_openj9-0.18.0.tar.gz"

  "14/linux/*":
    url:
      cn: "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/14/jdk/%{_arch}/linux/OpenJDK14U-jdk_%{_arch}_linux_openj9_14.0.2_12_openj9-0.21.0.tar.gz"

  "14/mac/*":
    url:
      cn: "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/14/jdk/%{_arch}/mac/OpenJDK14U-jdk_%{_arch}_mac_openj9_14.0.2_12_openj9-0.21.0.tar.gz"

  "14/win/*":
    url:
      cn: "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/14/jdk/%{_arch}/windows/OpenJDK14U-jdk_%{_arch}_windows_openj9_14.0.2_12_openj9-0.21.0.zip"

  "15/win/*":
    url:
      cn: "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/15/jdk/%{_arch}/windows/OpenJDK15U-jdk_%{_arch}_windows_openj9_15.0.2_7_openj9-0.24.0.zip"

  "15/darwin/*":
    url:
      cn: "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/15/jdk/%{_arch}/mac/OpenJDK15U-jdk_%{_arch}_mac_openj9_15.0.2_7_openj9-0.24.0.tar.gz"

  "15/linux/*":
    url:
      cn: "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/15/jdk/%{_arch}/linux/OpenJDK15U-jdk_%{_arch}_linux_openj9_15.0.2_7_openj9-0.24.0.tar.gz"

  "16/win/*":
    url:
      cn: "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/16/jdk/%{_arch}/windows/OpenJDK16U-jdk_%{_arch}_windows_hotspot_16.0.2_7.zip"


  "16/linux/*":
    url:
      cn: "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/16/jdk/%{_arch}/linux/ibm-semeru-open-jdk_%{_arch}_linux_16.0.2_7_openj9-0.27.0.tar.gz"


  "16/darwin/*":
    url:
      cn: "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/16/jdk/%{_arch}/mac/OpenJDK16U-jdk_%{_arch}_mac_hotspot_16.0.2_7.tar.gz"

  "17/win/*":
    url:
      cn: "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/17/jdk/%{_arch}/windows/OpenJDK17U-jdk_%{_arch}_windows_hotspot_17.0.2_8.zip"

  "17/darwin/*":
    url:
      cn: "https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/17/jdk/%{_arch}/mac/ibm-semeru-open-jdk_%{_arch}_mac_17.0.1_12_openj9-0.29.1.tar.gz"




















  "17/linux/*":
    url:
      cn:"%{tsinghua_url}/17/jdk/%{_arch}/%{_os}/OpenJDK17U-jdk_%{_arch}_linux_hotspot_17.0.2_8.tar.gz"

  "17/darwin/*":
    url:
      cn:"%{tsinghua_url}/17/jdk/%{_arch}/%{_os}/OpenJDK17U-jdk_%{_arch}_linux_hotspot_17.0.2_8.tar.gz"

  "17/win/*":
    _os: windows
    url:
      cn:"%{tsinghua_url}/17/jdk/%{_arch}/%{_os}/OpenJDK17U-jdk_%{_arch}_linux_hotspot_17.0.2_8.tar.gz"
