homepage: https://gitee.com/organizations/static-build/projects
license: MIT
rely: []

gh_url: https://github.com/x-cmd-build/kube-score/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/kube-score/-/releases/%{version}/downloads
file_suffix: 7z
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin:
  kube-score: kube-score%{bin_suffix}


rule:
  /*:
    version: stable

  stable/*:
    version: v0.0.0

  latest/*:
    version: v0.0.0


  "*/darwin/x64":
    zipname:    kube-score_1.16.1_darwin_amd64.tar.gz
  "*/darwin/arm64":
    zipname:    kube-score_1.16.1_darwin_arm64.tar.gz
  "*/linux/x64":
    zipname:    kube-score_1.16.1_linux_amd64.tar.gz
  "*/linux/arm64":
    zipname:    kube-score_1.16.1_linux_arm64.tar.gz
  "*/win/x64":
    zipname:    kube-score_1.16.1_windows_amd64.tar.gz
    bin_suffix: .exe