homepage: https://gitee.com/organizations/static-build/projects
license: MIT
rely: []

gh_url: https://github.com/x-cmd-build/tokei/releases/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/tokei/-/releases/%{version}/downloads
file_suffix: tar.xz
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin:
  tokei: tokei%{bin_suffix}


rule:
  /*:
    version: stable

  stable/*:
    version: v0.0.0

  latest/*:
    version: v0.0.0

  "*/darwin/x64":
    zipname:    tokei-x86_64-apple-darwin.tar.xz
  "*/darwin/arm64":
    zipname:    tokei-x86_64-apple-darwin.tar.xz
  "*/linux/x64":
    zipname:    tokei-x86_64-unknown-linux-gnu.tar.xz
  "*/linux/arm64":
    zipname:    tokei-aarch64-unknown-linux-gnu.tar.xz
  "*/win/x64":
    zipname:    tokei-x86_64-pc-windows-msvc.tar.xz
    xbin:
      tokei: tokei-x86_64-pc-windows-msvc
    bin_suffix: .exe