homepage: https://github.com/mpetuska/ktx
license: Apache License
rely: []
_os: "%{os}"
_arch: "%{arch}"
file_suffix: zip
url:
  internet: "https://github.com/mpetuska/ktx/releases/download/%{version}/ktx-%{version}.zip"
  cn: "https://github.com/mpetuska/ktx/releases/download/%{version}/ktx-%{version}.zip"
unpack_way: unpack_copy_to_target_dir

xbin:
  ktx: bin/ktx
rule:
  /*:
    version: stable

  stable/*:
    version: 0.1.2

  latest/*:
    version: 0.1.2

  "*/linux/arm64":


  "*/darwin/arm64":


  "*/linux/x64":


  "*/darwin/x64":


  "*/win/x64":






