homepage: https://strawberryperl.com/releases.html
license: MIT
rely: []

os-arch:
  linux-arrch:
    url:
      _: https://github.com/skaji/relocatable-perl/releases/download/%{version}/perl-%{arch}-%{os}.tar.gz
      cn: ""
  darwin/arm64:
    url:
      _: https://github.com/skaji/relocatable-perl/releases/download/%{version}/perl-%{arch}-%{os}.tar.gz
      cn: "https://github.com/skaji/relocatable-perl/releases/download/%{version}/perl-%{arch}-%{os}.tar.gz"
  linux/x64:
    url:
      _: https://github.com/skaji/relocatable-perl/releases/download/%{version}/perl-%{arch}-%{os}.tar.gz
      cn: "https://github.com/skaji/relocatable-perl/releases/download/%{version}/perl-%{arch}-%{os}.tar.gz"
  darwin/x64:
    url:
      _: https://github.com/skaji/relocatable-perl/releases/download/%{version}/perl-%{arch}-%{os}.tar.gz
      cn: ""
  win-64bit:
    url:
      _: https://strawberryperl.com/download/%{version}/strawberry-perl-%{version}-%{os}.zip
      cn: "https://strawberryperl.com/download/%{version}/strawberry-perl-%{version}-%{os}.zip"

xbin:
  perl: perl%{bin_suffix}
