homepage: https://strawberryperl.com/releases.html
license: MIT
rely: []
xbin:
  perl: perl%{bin_suffix}
_os: "%{os}"
_arch: "%{arch}"
file_suffix: tar.gz
perl_url: https://github.com/skaji/relocatable-perl/releases/download/
url:
  internet: https://github.com/skaji/relocatable-perl/releases/download/%{version}/perl-%{_os}-%{_arch}.tar.gz
  cn: https://github.com/skaji/relocatable-perl/releases/download/%{version}/perl-%{_os}-%{_arch}.tar.gz
file_suffix: tar.gz
hook:
  activate: activate.sh
  deactivate: deactivate.sh
unpack_way: unpack_copy_to_target_dir


rule:

  "*/win/*":
    version: 5.32.1.1

  "*/linux/*":
    version: 5.36.0.1

  "*/darwin/*":
    version: 5.36.0.1


  "*/win/x64":
    _arch: 64bit
    file_suffix: zip
    url:
      internet: https://strawberryperl.com/download/%{version}/strawberry-perl-%{version}-%{_arch}.%{file_suffix}
      cn: https://strawberryperl.com/download/%{version}/strawberry-perl-%{version}-%{_arch}.%{file_suffix}

  "*/win/x32":
    _arch: 32bit
    file_suffix: zip
    url:
      internet: https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-%{_arch}.%{file_suffix}
      cn: https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-%{_arch}.%{file_suffix}

  "*/linux/arm64":
    _os: linux
    _arch: aarch64
    url:
      internet: "%{perl_url}%{version}/perl-%{_arch}-%{_os}.tar.gz"
      cn: "%{perl_url}%{version}/perl-%{_arch}-%{_os}.tar.gz"

  "*/linux/x64":
    _os: linux
    _arch: x86_64
    url:
      internet: "%{perl_url}%{version}/perl-%{_arch}-%{_os}.tar.gz"
      cn: "%{perl_url}%{version}/perl-%{_arch}-%{_os}.tar.gz"

  "*/darwin/x64":
    _arch: 2level
    url:
      internet: "%{perl_url}%{version}/perl-%{_os}-%{_arch}.tar.gz"
      cn: "%{perl_url}%{version}/perl-%{_os}-%{_arch}.tar.gz"

  "*/darwin/arm64":
    _arch: 2level
    url:
      internet: "%{perl_url}%{version}/perl-%{_os}-%{_arch}.tar.gz"
      cn: "%{perl_url}%{version}/perl-%{_os}-%{_arch}.tar.gz"

  "*/darwin/amd64":
    _arch: 2level
    url:
      internet: "%{perl_url}%{version}/perl-%{_os}-%{_arch}.tar.gz"
      cn: "%{perl_url}%{version}/perl-%{_os}-%{_arch}.tar.gz"

  "5.36.0.1/linux/x64":
    _arch: arm64
    url:
      internet: "%{perl_url}%{version}/perl-%{_os}-%{_arch}.tar.gz"
      cn: "%{perl_url}%{version}/perl-%{_os}-%{_arch}.tar.gz"

  "5.36.0.1/linux/arm64":
    _arch: "%{arch}"
    url:
      internet: "%{perl_url}%{version}/perl-%{_os}-arm64.tar.gz"
      cn: https://github.com/skaji/relocatable-perl/releases/download/%{version}/perl-%{_os}-arm64.tar.gz

  "5.36.0.1/linux/amd64":
    _arch: "%{arch}"
    url:
      internet: https://github.com/skaji/relocatable-perl/releases/download/%{version}/perl-%{_os}-amd64.tar.gz
      cn: https://github.com/skaji/relocatable-perl/releases/download/%{version}/perl-%{_os}-amd64.tar.gz

  "5.36.0.1/darwin/amd64":
    _arch: "%{arch}"
    url:
      internet: https://github.com/skaji/relocatable-perl/releases/download/%{version}/perl-%{_os}-amd64.tar.gz
      cn: https://github.com/skaji/relocatable-perl/releases/download/%{version}/perl-%{_os}-amd64.tar.gz

  "5.36.0.1/darwin/arm64":
    url:
      internet: https://github.com/skaji/relocatable-perl/releases/download/%{version}/perl-%{_os}-arm64.tar.gz
      cn: https://github.com/skaji/relocatable-perl/releases/download/%{version}/perl-%{_os}-arm64.tar.gz

