homepage: https://strawberryperl.com/releases.html
license: MIT
rely: []
xbin:
  perl: perl%{bin_suffix}
_os: "%{os}"
_arch: "%{arch}"
file_suffix: tar.gz
url:
  _: https://github.com/skaji/relocatable-perl/releases/download/%{version}/perl-%{_arch}-%{_os}.tar.gz
  cn: "https://github.com/skaji/relocatable-perl/releases/download/%{version}/perl-%{_arch}-%{_os}.tar.gz"
hook:
  activate: activate
  deactivate: deactivate



rules:
  "*/linux/arch64":


  "*/darwin/*":
    _os: darwin-2level
    url:
      _: https://github.com/skaji/relocatable-perl/releases/download/%{version}/perl-%{_os}.%{file_suffix}
      cn: "https://github.com/skaji/relocatable-perl/releases/download/%{version}/perl-%{_os}.%{file_suffix}"


  "*/linux/x64":
    _os: x86_64
    url:
      _: "https://github.com/skaji/relocatable-perl/releases/download/%{version}/perl-%{_arch}-%{_os}.%{file_suffix}"
      cn: "https://github.com/skaji/relocatable-perl/releases/download/%{version}/perl-%{_arch}-%{_os}.%{file_suffix}"

  "*/win/x64":
    _arch: 64bit
    file_suffix: zip
    url:
      _: https://strawberryperl.com/download/%{version}/strawberry-perl-%{version}-%{_arch}.%{file_suffix}
      cn: "https://strawberryperl.com/download/%{version}/strawberry-perl-%{version}-%{_arch}.%{file_suffix}"
