homepage: https://strawberryperl.com/releases.html
license: MIT
rely: []
xbin:
  perl: perl%{bin_suffix}
_os: "%{os}"
_arch: "%{arch}"
file_suffix: tar.gz
url:
  internet: https://www.cpan.org/src/5.0/perl-%{version}.tar.gz
  cn: "https://www.cpan.org/src/5.0/perl-%{version}.tar.gz"
file_suffix: tar.gz
hook:
  activate: activate.sh
  deactivate: deactivate.sh
unpack_way: unpack_copy_to_target_dir


rule:

  /win/*:
    version: 5.32.1.1

  /linux/*:
    version: 5.34.1.1

  /darwin/*:
    version: 5.34.1.1


  "*/win/x64":
    _arch: 64bit
    file_suffix: zip
    url:
      _: https://strawberryperl.com/download/%{version}/strawberry-perl-%{version}-%{_arch}.%{file_suffix}
      cn: https://strawberryperl.com/download/%{version}/strawberry-perl-%{version}-%{_arch}.%{file_suffix}

  "*/win/x32":
    _arch: 32bit
    file_suffix: zip
    url:
      _: https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-%{_arch}.%{file_suffix}
      cn: https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-%{_arch}.%{file_suffix}

  "*/linux/x64":
    _os: linux
    _arch: x86_64
    url:
      _: https://github.com/skaji/relocatable-perl/releases/download/%{version}/perl-%{_arch}-%{_os}.tar.gz
      cn: https://github.com/skaji/relocatable-perl/releases/download/%{version}/perl-%{_arch}-%{_os}.tar.gz

  "*/darwin/x64":
    _arch: 2level
    _os: darwin
    url:
      _: https://github.com/skaji/relocatable-perl/releases/download/%{version}/perl-%{_os}-%{_arch}.tar.gz
      cn: https://github.com/skaji/relocatable-perl/releases/download/%{version}/perl-%{_os}-%{_arch}.tar.gz

  "*/darwin/amd64":
    _arch: 2level
    _os: darwin
    url:
      _: https://github.com/skaji/relocatable-perl/releases/download/%{version}/perl-%{_os}-%{_arch}.tar.gz
      cn: https://github.com/skaji/relocatable-perl/releases/download/%{version}/perl-%{_os}-%{_arch}.tar.gz
