homepage: https://strawberryperl.com/releases.html
license: MIT
rely: []
xbin:
  perl: perl%{bin_suffix}
_os: "%{os}"
_arch: "%{arch}"
file_suffix: tar.gz
url:
  _: https://www.cpan.org/src/5.0/perl-%{version}.tar.gz
  cn: "https://www.cpan.org/src/5.0/perl-%{version}.tar.gz"

hook:
  activate: activate.sh
  deactivate: deactivate.sh


rule:

  /win/*:
    version: 5.32.1.1

  "*/win/x86":
    _arch: 64bite
    url: https://strawberryperl.com/download/%{version}/strawberry-perl-%{version}-%{_arch}.zip

  "*/win/x86":
    _arch: 64bit
    url: https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-64bit.zip


  "*/win/x64":
    _os: 64bit
    url: https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-64bit.zip
