homepage: https://strawberryperl.com/releases.html
license: MIT
rely: []
xbin:
  perl: perl%{bin_suffix}
_os: "%{os}"
_arch: "%{arch}"
file_suffix: tar.gz
url:
  _: https://www.cpan.org/src/5.0/perl-%{version}.tar.gz
  cn: "https://www.cpan.org/src/5.0/perl-%{version}.tar.gz"

hook:
  activate: activate.sh
  deactivate: deactivate.sh
  install: post_install.sh


rule:

  /*:
    version: 5.36.0-RC3

  "*/darwin/*":
    _os: aarch64

