homepage: https://gitee.com/organizations/static-build/projects
license: MIT

gh_url: https://github.com/x-cmd-builder/sodium/releases/download/%{version}/
gc_url: https://gitcode.net/x-cmd-builder/sodium/-/releases/%{version}/downloads
file_suffix: 7z
url:
  en: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin:
  sodium: sodium

rule:
  /*:
    version: stable

  stable/*:
    version: v0.0.1

  latest/*:
    version: v0.0.1

  "*/linux/arm64":
    zipname:    linux.7z

  "*/darwin/arm64":
    zipname:    macos_arm64.7z

  "*/linux/x64":
    zipname:    linux.7z

  "*/darwin/x64":
    zipname:    macos_x64.7z

  "*/win/x64":
    zipname:    windows.7z
    xbin:       sodium.exe
