homepage: https://github.com/mpetuska/ktx
license: Apache License
rely: []
_os: "%{os}"
_arch: "%{arch}"
file_suffix: zip
url:
  internet: "https://github.com/moditect/layrry/releases/download/v%{version}/layrry-%{version}.zip"
  cn: "https://github.com/moditect/layrry/releases/download/v%{version}/layrry-%{version}.zip"
unpack_way: unpack_copy_to_target_dir

xbin:
  layrry: bin/layrry
rule:
  /*:
    version: stable

  stable/*:
    version: 1.0.0.Alpha2

  latest/*:
    version: 1.0.0.Alpha2

  "*/linux/arm64":


  "*/darwin/arm64":


  "*/linux/x64":


  "*/darwin/x64":


  "*/win/x64":






