homepage: https://nodejs.org
license: MIT
rely: []
node_source: https://nodejs.org/dist/%{version}
file_suffix: tar.gz
url:
  internet: "%{node_source}/node-%{version}-%{os}-%{arch}.%{file_suffix}"
  cn: "https://registry.npmmirror.com/-/binary/node/latest-%{version_pre}/node-%{version}-%{os}-%{arch}.%{file_suffix}"

  node: bin/node
  npm: bin/npm

hook:
  activate: activate.sh
  deactivate: deactivate.sh
  install: install.sh

unpack_way: unpack_copy_to_target_dir

rule:

  /*:
    version: latest

  latest/*:
    version_pre: v18.x
    version: v18.4.0

  "*/linux/x64":

  "*/linux/arm64":

  "*/darwin/x64":

  "*/darwin/arm64":

  "*/win/x64":

  v19*/*/*:
    version_pre: v19.x


  v18*/*/*:
    version_pre: v18.x


  v17*/*/*:
    version_pre: v17.x


  v16*/*/*:
    version_pre: v16.x

  v15*/*/*:
    version_pre: v15.x


  v14*/*/*:
    version_pre: v14.x

  v13*/*/*:
    version_pre: v13.x

  v12*/*/*:
    version_pre: v12.x

  v11*/*/*:
    version_pre: v11.x

  v10*/*/*:
    version_pre: v10.x

  v0.12*/*/*:
    version_pre: v0.12.x

  v0.10*/*/*:
    version_pre: v0.10.x






  v19/*/*:
    version: v19.5.0

  v18/*/*:
    version: v18.4.0

  v17/*/*:
    version: v17.9.1

  v16/*/*:
    version: v16.19.0


  v*/win:
    file_suffix: zip
    bin_suffix: exe
