homepage: https://nodejs.org
license: MIT
rely: []
bin: {}
const:
  node_source: https://nodejs.org/dist/%{version}
  tuna_source: https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/%{version}
file_suffix: tar.gz
url:
  _: '%{node_source}/node-%{version}-%{os}-%{arch}.${file_suffix}'
  cn: '%{tuna_source}/node-%{version}-%{os}-%{arch}.${file_suffix}'
rule:
  v*/win*:
    file_suffix: zip

  stable/*:
    version: v14.0.3

  # "v(1[0-4]|[0-9])(\\..+)?/darwin":
  "!v1*.*/darwin-arm64":
    osarch: darwin-x64
  "v10.*/darwin-arm64":
    osarch: darwin-x64
  "v11.*/darwin-arm64":
    osarch: darwin-x64
  "v12.*/darwin-arm64":
    osarch: darwin-x64
  "v13.*/darwin-arm64":
    osarch: darwin-x64
  "v14.*/darwin-arm64":
    osarch: darwin-x64


