homepage: https://nodejs.org
license: MIT
rely: []
node_source: https://nodejs.org/dist/%{version}
tuna_source: https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/%{version}
file_suffix: tar.gz
url:
  _: "%{node_source}/node-%{version}-%{os}-%{arch}.%{file_suffix}"
  cn: "%{tuna_source}/node-%{version}-%{os}-%{arch}.%{file_suffix}"
xbin:
  node: bin/node
  npm: bin/npm

hook:
  activate: activate.sh
  deactivate: deactivate.sh
  install: post-install.sh

rule:

  /*:
    version: latest

  latest/*:
    version: v18.2.0

  v*/win:
    file_suffix: zip
    bin_suffix: exe
