homepage: https://nodejs.org
license: MIT
rely: []
bin: {}
const:
  node_source: https://nodejs.org/dist/%{version}
  tuna_source: https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/%{version}
url:
  _: '%{node_source}/node-%{version}-%{os}-%{arch}.tar.gz'
  cn: '%{tuna_source}/node-%{version}-%{os}-%{arch}.tar.gz'
os-arch:
  linux-arm64: {}
  darwin-arm64:
    url:
      _: '%{node_source}/node-%{version}-darwin-x64.tar.gz'
      cn: '%{tuna_source}/node-%{version}-darwin-x64.tar.gz'
  linux-x64: {}
  darwin-x64: {}
  win-x64:
    url:
      _: '%{node_source}/node-%{version}-%{os}-%{arch}.zip'
      cn: '%{tuna_source}/node-%{version}-%{os}-%{arch}.zip'
  win-arm64:
    url:
      _: '%{node_source}/node-%{version}-%{os}-%{arch}.zip'
      cn: '%{tuna_source}/node-%{version}-%{os}-%{arch}.zip'
