homepage: https://www.scala-sbt.org/download.html
license: Apache License
rely: []
_os: "%{os}"
_arch: "%{arch}"
file_suffix: zip
url:
  internet: "https://github.com/sbt/sbt/releases/download/v%{version}/sbt-%{version}.zip"
  cn: "https://github.com/sbt/sbt/releases/download/v%{version}/sbt-%{version}.zip"
unpack_way: unpack_copy_to_target_dir

xbin:
  sbt: bin/sbt

rule:
  /*:
    version: stable

  stable/*:
    version: "1.8.2"

  latest/*:
    version: "1.8.2"

  "*/linux/arm64":


  "*/darwin/arm64":


  "*/linux/x64":


  "*/darwin/x64":


  "*/win/x64":


