homepage: https://golang.google.cn
license: MIT
rely: []

gh_url: https://github.com/x-cmd-build/tig/releases/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/tig/-/releases/%{version}/downloads
file_suffix: 7z
static-build: tig/tig
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin:
  tig: tig.%{os}.%{arch}%{bin_suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: v0.0.0

  latest/*:
    version: v0.0.0

  "*/linux/arm64":
    zipname:    tig.linux.arm64.7z
  "*/darwin/arm64":
    zipname:    tig.darwin.arm64.7z
  "*/linux/x64":
    zipname:    tig.linux.x64.7z
  "*/darwin/x64":
    zipname:    tig.darwin.x64.7z
  "*/win/x64":
    zipname:    tig.win.x64.exe.7z
    bin_suffix: .exe


