homepage: https://golang.google.cn
license: MIT
rely: []

gh_url: https://raw.githubusercontent.com/static-build/tig/main/tig/%{version}
gc_url: https://gitee.com/static-build/tig/raw/main/tig/%{version}
file_suffix: 7z
static-build: tig/tig
url:
  _: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin:
  tig: tig.%{os}.%{arch}%{bin_suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: 2.5.5

  latest/*:
    version: 2.5.5

  "*/linux/arm64":
    zipname:    tig.linux.arm64.7z
  "*/darwin/arm64":
    zipname:    tig.darwin.arm64.7z
  "*/linux/x64":
    zipname:    tig.linux.x64.7z
  "*/darwin/x64":
    zipname:    tig.darwin.x64.7z
  "*/win/x64":
    zipname:    tig.win.x64.exe.7z
    bin_suffix: .exe


  https://gitee.com/static-build/p7zip/blob/main/7za/16.02/7za.linux.x64.7z