homepage: https://github.com/grails/grails-core/releases
license: Apache License
rely: []
_os: "%{os}"
_arch: "%{arch}"
file_suffix: zip
url:
  internet: "https://github.com/grails/grails-core/releases/download/v%{version}/grails-%{version}.zip"
  cn: "https://github.com/grails/grails-core/releases/download/v%{version}/grails-%{version}.zip"
unpack_way: unpack_copy_to_target_dir
xbin:
  grails: bin/grails
rule:
  /*:
    version: stable

  stable/*:
    version: v5.3.2

  latest/*:
    version: v5.3.2

  "*/linux/arm64":

  "*/darwin/arm64":

  "*/linux/x64":

  "*/darwin/x64":

  "*/win/x64":




