homepage: https://gitee.com/organizations/static-build/projects
license: MIT
rely: []

gh_url: https://raw.githubusercontent.com/static-build/nmap/main/ncat/%{version}
gc_url: https://gitee.com/static-build/nmap/raw/main/ncat/%{version}
file_suffix: 7z
static-build: nmap/ncat
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin: ncat.%{os}.%{arch}%{bin_suffix}

rule:
  /*:
    version: stable

  stable/*:
    version: 7.92

  latest/*:
    versin: 7.92

  "*/linux/arm64":
    zipname:    ncat.linux.arm64.7z
  "*/darwin/arm64":
    zipname:    ncat.darwin.arm64.7z
  "*/linux/x64":
    zipname:    ncat.linux.x64.7z
  "*/darwin/x64":
    zipname:    ncat.darwin.x64.7z
  "*/win/x64":
    url:
      internet: "%{gh_url}/%{zipname}"
      cn: ""