license: MIT
rely: []
file_suffix: tar.gz
url:
  _: "https://sourceforge.net/projects/luabinaries/files/%{version}/Tools%20Executables/lua-%{version}_%{_os}%{_arch}_bin.%{file_suffix}/download"
  cn: "https://sourceforge.net/projects/luabinaries/files/%{version}/Tools%20Executables/lua-%{version}_%{_os}%{_arch}_bin.%{file_suffix}/download"

hook:
  activate: activate.sh
  deactivate: deactivate.sh

xbin:
  lua: lua54

rule:
  /*:
    version: latest
  latest/*:
    version: 5.4.2

  "*/win":
    file_suffix: zip
    bin_suffix: exe

  "*/linux/*":
    _os: Linux
    _arch: "319_64"
  5.4.2/linux/*:
    _arch: "54_64"

  "*/win/x64":
    _os: Win
    _arch: 64
  "*/win/x32":
    _os: Win
    _arch: 32

  "*/mac/*":
    version: 5.2.4
    _os: MacOS
    _arch: 1011

  5.4.2/*:
    xbin: lua54
  5.3.6/*:
    xbin: luac53
  5.2.4/*:
    xbin: luac52
  5.1.5/*:
    xbin: luac5.1
