license: MIT
rely: []
file_suffix: tar.gz
url:
  internet: "https://sourceforge.net/projects/luabinaries/files/%{version}/Tools%20Executables/lua-%{version}_%{_os}%{_arch}_bin.%{file_suffix}/download"
  cn: "https://sourceforge.net/projects/luabinaries/files/%{version}/Tools%20Executables/lua-%{version}_%{_os}%{_arch}_bin.%{file_suffix}/download"


xbin:
  lua: lua54
hook:
  activate: activate.sh
  deactivate: deactivate.sh
rule:
  /*:
    version: latest
  latest/linux/*:
    version: 5.4.2

  latest/win/*:
    version: 5.4.2

  latest/darwin/*:
    version: 5.3.5

  "*/win":
    file_suffix: zip
    bin_suffix: exe

  "*/linux/x64":
    _os: Linux
    _arch: "319_64"

    "*/linux/arm64":
    _os: Linux
    _arch: "319_64"

  5.4.2/linux/*:
    _arch: "54_64"

  "*/win/x64":
    _os: Win
    _arch: 64
  "*/win/x32":
    _os: Win
    _arch: 32


  "5.3*/darwin/arm64":
    _os: MacOS
    _arch: 1011
    url:
      internet: "https://sourceforge.net/projects/luabinaries/files/%{version}/Other%20Libraries/lua-%{version}_MacOS_arch_lib.tar.gz/download"
      cn: "https://sourceforge.net/projects/luabinaries/files/%{version}/Other%20Libraries/lua-%{version}_MacOS%{_arch}_lib.tar.gz/download"

  "5.3*/darwin/x64":
    _os: MacOS
    _arch: 1011
    url:
      internet: "https://sourceforge.net/projects/luabinaries/files/%{version}/Other%20Libraries/lua-%{version}_MacOS_arch_lib.tar.gz/download"
      cn: "https://sourceforge.net/projects/luabinaries/files/%{version}/Other%20Libraries/lua-%{version}_MacOS%{_arch}_lib.tar.gz/download"




  "5.3.5/darwin/x64":
    _os: MacOS
    _arch: 1013
    url:
      internet: "https://sourceforge.net/projects/luabinaries/files/%{version}/Other%20Libraries/lua-%{version}_MacOS_arch_lib.tar.gz/download"
      cn: "https://sourceforge.net/projects/luabinaries/files/%{version}/Other%20Libraries/lua-%{version}_MacOS%{_arch}_lib.tar.gz/download"

    "5.3.5/darwin/arm64":
      _os: MacOS
      _arch: 1013
      url:
        internet: "https://sourceforge.net/projects/luabinaries/files/%{version}/Other%20Libraries/lua-%{version}_MacOS_arch_lib.tar.gz/download"
        cn: "https://sourceforge.net/projects/luabinaries/files/%{version}/Other%20Libraries/lua-%{version}_MacOS%{_arch}_lib.tar.gz/download"



  5.4*/linux/*:
    xbin: lua54
  5.4*/win/*:
    xbin: lua54
  5.3*/*/*:
    xbin: luac53
  5.3*/win/*:
    xbin: luac53

  5.34/darwin/*:
  xbin: liblua53.a

  5.32/darwin/*:
  xbin: liblua53.a