
name: Bundle x-cmd pkg
on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  Bundle:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      ___X_CMD_GHACTION_X: x1
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: agent-zero
      git_email: 0@x-cmd.com
      CONCURRENCY: 10
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: |
            xrc pkg && xws table internet && \
            git add "$(x wsroot)/doc"     && \
            git commit -m "update pkg available url markdown. by $GITHUB_RUN_NUMBER" && \
            git push git@github.com:x-cmd/pkg main



