name: Bundle x-cmd pkg

on:
  workflow_dispatch:

jobs:
  Bundle:
    runs-on: ubuntu-latest
    timeout-minutes: 100
    steps:
      - name: main
        uses: actions/checkout@v2
        with:
          code: |
            xws pkg yml2tgz
            xws push all




