
name: test xbin darwin
on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  test-linux:
    name: Build
    strategy:
      matrix:
        os: [ windows-2019, ubuntu-latest, macos-latest ]
        # os: [ gentoo ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 100
    env:
      ___X_CMD_GHACTION_X: x1
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: agent-zero
      git_email: 0@x-cmd.com
      CONCURRENCY: 10
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: |
            x ls && git pull && x os name && x os arch
            # xrc pkg && xws test_xbin linux/x64 linux/arm64 && xws push test




