name:  pkg
on:
  push:
  workflow_dispatch:

jobs:
  pkg_test:
    runs-on: ${{ matrix.os }}
    strategy:
       matrix:
        os: ubuntu-latest
    env:
      ___X_CMD_GHACTION_X: x1
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: mnnna
      git_email: zhengyuhang@x-cmd.com
      CONCURRENCY: 10
     steps:
    - uses: actions/checkout@v3
    - run: echo hello > path/to/artifact/world.txt
      

