name:  pkg
on:
  push:
  workflow_dispatch:

jobs:
  pkg:
    runs-on: ${{ matrix.os }}
    strategy:
       matrix:
        os: ubuntu-latest
    timeout-minutes: 5
    env:
      ___X_CMD_GHACTION_X: x1
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: mnnna
      git_email: zhengyuhang@x-cmd.com
      CONCURRENCY: 10
     steps:
      - name: main
        uses: x-cmd/action@main
        with:
         code: |
          xws generate_table net

