
name: test xbin
on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:
  workflow_call:

jobs:
  test-linux:
    name: Build
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        # os: [ windows-2019, ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    env:
      # 设置一个名为GITHUB_TOKEN的变量，值为仓库中的一个密钥，用于访问GitHub API。
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # 设置一个名为ssh_key的变量，值为仓库中的一个密钥，用于SSH连接。
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      # 设置一个名为git_user的变量，值为lunrenyi，用于Git操作的用户名。
      git_user: lunrenyi
      # 设置一个名为git_email的变量，值为lxb2863854515@163.com，用于Git操作的邮箱。
      git_email: lxb2863854515@163.com
      CONCURRENCY: 10
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: |
            xrc pkg && xws test_xbin internet && git pull && xws push test