
name: test xbin darwin
on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  test-darwin:
    runs-on: macos-latest
    timeout-minutes: 100
    env:
      ___X_CMD_GHACTION_X: x1
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: agent-zero
      git_email: 0@x-cmd.com
      CONCURRENCY: 10
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: |
            xrc pkg && xws test_xbin darwin/x64 darwin/arm64 && xws push test
  test-windows:
    runs-on: windows-latest
    timeout-minutes: 100
    env:
      ___X_CMD_GHACTION_X: x1
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: agent-zero
      git_email: 0@x-cmd.com
      CONCURRENCY: 10
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: |
            xrc pkg && xws test_xbin win/x64 && xws push test
  test-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 100
    env:
      ___X_CMD_GHACTION_X: x1
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: agent-zero
      git_email: 0@x-cmd.com
      CONCURRENCY: 10
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: |
            xrc pkg && xws test_xbin linux/x64 linux/arm64 && xws push test




