
name: test xbin
on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  test-linux:
    name: Build
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        # os: [ windows-2019, ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    env:
      ___X_CMD_GHACTION_X: x1
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: agent-zero
      git_email: 0@x-cmd.com
      CONCURRENCY: 10
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: |
            xrc pkg && xws test_xbin internet && git pull && xws push test