homepage: https://www.php.net/
license: MIT
rely: []
file_suffix: tar.gz
en_source: "https://www.php.net/distributions/"
cn_source: "https://mirrors.sohu.com/php/"

url:
  en: '%{en_source}php-%{version}.%{file_suffix}'
  cn: '%{cn_source}php-%{version}.%{file_suffix}'

hook:
  activate: activate.sh
  deactivate: deactivate.sh
unpack_way: unpack_copy_to_target_dir
xbin:
    php: main/php.h

hook:
  activate: activate.sh
  deactivate: deactivate.sh

rule:

  /*:
    version: 8.2.1

  "*/darwin/arm64":


  "*/linux/x64":



  "*/win/x64":
    _os: pc-windows-msvc
    _arch: x86_64

  "*/darwin/x64":

