homepage: https://gitee.com/organizations/static-build/projects
license: MIT
rely: []

gh_url: https://github.com/x-cmd-build/brook/download/%{version}
gc_url: https://gitcode.net/x-cmd-build/brook/-/releases/%{version}/downloads
file_suffix: tar.xz
url:
  internet: "%{gh_url}/%{zipname}"
  cn: "%{gc_url}/%{zipname}"

xbin:
  brook: brook.%{os}.%{arch}%{bin_suffix}


rule:
  /*:
    version: stable

  stable/*:
    version: v0.0.0

  latest/*:
    version: v0.0.0

  "*/darwin/arm64":
    zipname:    brook_darwin_arm64.tar.xz
  "*/darwin/x64":
    zipname:    brook_darwin_amd64.tar.xz
  "*/linux/x64":
    zipname:    brook_linux_amd64.tar.xz
  "*/linux/arm64":
    zipname:    brook_linux_arm64.tar.xz
  "*/win/x64":
    zipname:    brook_windows_amd64.tar.xz
    bin_suffix: .exe